import { cursosPresencialModel } from './models/presencial.model';

// export class cursosPresencial {
    export const PresencialCursosMock: Array <cursosPresencialModel> = [
 
        {
            "nomeCurso": "Aperfeiçoamento em Cosmetologia Estética",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "6 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/estetica.jpg",
            "area": "saude",
            "publicoAlvo": "Profissionais com formação superior em estética e cosmética, biomedicina, fisioterapia e nas demais áreas afins.",
            "competencias": "Ao término do curso, o profissional estará apto a: Analisar as formulações cosméticas correlacionando-as aos tratamentos estéticos faciais, capilares e corporais; Selecionar os nutracêuticos (nutricosméticos) apropriados, associando-os aos tratamentos estéticos; Aplicar as melhores soluções para os tratamentos estéticos; Construir uma visão ampla do empreendedorismo na área de Estética.",
            "diferencial": "O curso de Cosmetologia Estética destaca-se por aplicar práticas laboratoriais de formulação cosmética e de tratamentos estéticos, além de focar em nutricosméticos, com ativos inovadores, para potencializar os tratamentos; apresentar os cosméticos orgânicos e veganos, em expansão no mercado, como opções para os tratamentos estéticos; destaca temas relacionados ao empreendedorismo e à gestão de equipes no setor da estética.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Direito do Trabalho",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Segunda e Quarta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/direito.jpg",
            "area": "direito",
            "publicoAlvo": "Profissionais com formação superior em Direito.",
            "competencias": "O curso de Aperfeiçoamento em Direito do Trabalho concentra-se no estudo dos novos institutos inseridos na CLT pela Lei 13.467/17 e na sua compatibilização com os princípios fundadores do Direito do Trabalho. As disciplinas da trilha comum apresentam contornos fortemente interdisciplinares, estimulando a reflexão sistêmica do Direito do Trabalho. As disciplinas presenciais e EaD oferecem conhecimentos práticos atualizados com a reforma trabalhista, fomentando a boa prática na advocacia trabalhista.",
            "diferencial": "O curso de Aperfeiçoamento em Direito do Trabalho da Unigranrio possui um projeto pedagógico integralmente ajustado às alterações implementadas pela reforma trabalhista. As disciplinas abordam conteúdos interdisciplinares que complementam diretamente a formação do profissional que pretende atuar no âmbito do Direito do Trabalho. Além disso, o curso ainda reforça o desempenho dos interessados em concursos públicos para Magistratura do Trabalho, Ministério Público do Trabalho ou outros cargos nos Tribunais do Trabalho. Por oferecer parte das disciplinas em EaD, viabiliza-se a rápida conclusão do curso.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Docência do Ensino Superior",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Segunda e Quarta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/servico_social.jpg",
            "area": "educacao",
            "publicoAlvo": "Graduados em todas as áreas de conhecimento, que atuam ou que desejam atuar na carreira docente no Ensino Superior.",
            "competencias": "Desenvolver a construção das competências profissionais acerca do trabalho pedagógico no Ensino Superior. Construir práticas de ensino a partir de perspectivas metodológicas para atuação no Ensino Superior.",
            "diferencial": "Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas, além dos principais profissionais de mercado desenvolvendo aulas teóricas e práticas, permitindo, assim, a condição de um aprendizado diferenciado na arte da licenciatura.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da Regulação Federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Enfermagem em Emergência Pré-Hospitalar",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "6 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/enfermagem.jpg",
            "area": "saude",
            "publicoAlvo": "Enfermeiros que querem se aperfeiçoar no atendimento as vítimas e doentes com agravos de urgência e emergência de saúde no ambiente pré-hospitalar.",
            "competencias": "Ao final do curso, o aluno estará apto a compreender, organizar e desenvolver o processo de trabalho no contexto das situações de urgência e emergência, na perspectiva da atenção à saúde no atendimento pré-hospitalar. Reconhecer as situações de urgência e emergência com os instrumentos que condicionam e/ou determinam o processo de trabalho. Atuar nas situações de urgência e emergência com embasamento teórico-prático, visão crítica e reflexiva, reconhecendo as prioridades no atendimento ao indivíduo no ambiente pré-hospitalar e no cenário de múltiplas e desastres.",
            "diferencial": "Utilização de manuais e protocolos atualizados junto a American Heart Association ¿ AHA e Society Trauma for Nurses ¿ STN. Utilização de metodologias ativas de ensino com foco em simulação realística em laboratório especializado.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Farmácia Clínica",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "6 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/farmacia.jpg",
            "area": "saude",
            "publicoAlvo": "Profissionais com Formação Superior em Farmácia.",
            "competencias": "O curso tem como objetivo desenvolver habilidades para implementação e gerenciamento dos serviços Farmacêuticos no âmbito Clínico. Interagir com a equipe multiprofissional em saúde, garantindo o uso racional de medicamento e promovendo a Farmacoeconomia. Implantar projetos e protocolos clínicos, aumentando a qualidade da assistência Farmacêutica.",
            "diferencial": "Pós-Graduação com disciplinas ministradas por profissionais qualificados e atuantes na profissão.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Gestão de Finanças",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "Sábado: 08:00 às 14:00 / Dias da Semana: 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/adm.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de recursos financeiros como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso, o participante estará apto a desenvolver políticas de gestão financeira que atendam às especificidades do mercado.",
            "diferencial": "Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Gestão de Logística Integrada",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/logistica.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de recursos financeiros como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso, o participante estará apto a implementar estratégias logísticas que assegurem a disponibilização de bens e serviços, a partir da adequação dos fluxos de informações e físicos.",
            "diferencial": "Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Gestão de Marketing",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Segunda e Quarta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "Sábado:  / Dias de Semana: 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/marketing.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso, o participante estará apto a compreender o mercado, planejar o composto de marketing e a desenvolver e implementar estratégias mercadológicas, de forma a potencializar os recursos organizacionais, conforme previsto no plano de marketing.",
            "diferencial": "Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Gestão de Moda",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Segunda e Quarta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/design_moda.jpg",
            "area": "moda",
            "publicoAlvo": "Profissionais portadores de diploma de nível superior em diversas áreas principalmente Moda, Comunicação, Administração, Marketing, Design ou que estejam direta ou indiretamente ligadas à área de moda.",
            "competencias": "Apresentar e discutir a cadeia de negócios de moda, com os aspectos de Supply Chain e seus ciclos de integração com as diversas etapas de criação e processos produtivos e a integração com o ambiente de mercado e o impacto dos ciclos de lançamentos das coleções sobre os negócios das empresas. Capacitar e aprimorar o profissional da área - por meio de aulas expositivas, atividades práticas e discussões - fornecendo uma visão sistêmica, para atuar em diversos segmentos da moda, sobretudo, abrir seu próprio negócio, promover a atuação como gestor na cadeia de produção, distribuição, divulgação e comercialização dos produtos de moda, desenvolvendo estratégias de negócios e marketing. Ao final do curso o participante estará apto a compreender o mercado de moda com suas etapas, complexidades e interações de áreas de conhecimento e de impacto no ambiente e nos negócios e dominar as distintas atividades, o que o capacitará a atuar em diferentes ambientes do negócio.",
            "diferencial": "O curso de Pós-Graduação em Negócios da Moda proporciona aos alunos conhecimentos sólidos em planejamento e gestão de negócios, de produtos e de marcas de moda, bem como o entendimento da comunicação, da linguagem e da cultura da moda. O egresso torna-se apto para atuar na gestão da cadeia têxtil relacionada aos negócios da moda, com capacidade crítica e visão estratégica do mercado, necessários ao contexto atual.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Gestão de Pessoas",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Segunda e Quarta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/rh.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de capital humano como fonte de vantagens competitivas.",
            "competencias": "O participante estará apto a compreender o impacto da correta gestão de recursos humanos no que tange a liderança, proatividade e comprometimento no sucesso da empresa.",
            "diferencial": "Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Gestão de Processos",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/processos_gerenciais.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com formação superior que almejam atuar na melhoria dos processos das organizações onde atuam.",
            "competencias": "Ao término do curso, o profissional estará apto a combinar as técnicas de gestão de processos, visando o aprimoramento da administração de recursos humanos, materiais e financeiros das organizações.",
            "diferencial": "O curso de Gestão de Processos oferece disciplinas direcionadas às práticas de gestão dos processos de uma organização, visando a análise e a melhoria dos mesmos, o que pode tornar as empresas mais competitivas a partir de estratégias eficazes que incluem a redução de desperdícios de tempo, mão de obra, materiais, entre outras. Forma empreendedores capazes de gerenciar, com mais efetividade, os processos das empresas.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Gestão Tributária",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias / Fatenp/Nova Palhoça IX",
            "diasAula": "Segunda e Quarta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/ciencias_contabeis.jpg",
            "area": "gestao",
            "publicoAlvo": "Graduados em Ciências Contábeis, ou áreas afins com experiência de mercado. Empreendedores e gestores de empresas.",
            "competencias": "O curso busca capacitar profissionais na área de Gestão Tributária através da consolidação de conceitos e práticas contemporâneas voltadas a compreender, de forma abrangente, a gestão organizacional. Promove a compreensão acerca dos meandros da Contabilidade Trabalhista e Previdenciária, bem como de Auditoria Fiscal e Tributária. Fornece ferramentas para aplicação de Planejamento Tributário para Decisão, Controle e Gestão Estratégica Empresarial.",
            "diferencial": "O curso de Aperfeiçoamento em Gestão Tributária visa proporcionar o domínio de técnicas de tributos (Federais, Estaduais e Municipais), bem como esclarecer quais os seus reflexos e impactos frente ao Direito Trabalhista e Previdenciário.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Hemato-Imunodiagnóstico",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "6 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/biomedicina.jpg",
            "area": "saude",
            "publicoAlvo": "Graduados em ciências biológicas, farmácia, biomedicina, nutrição e medicina veterinária.",
            "competencias": "Ao final do curso, o profissional está apto a aplicar e propor técnicas de bioquímica e uranálise, hematologia, imunologia e biologia molecular. O curso propicia condições para uma análise interdisciplinar no diagnóstico laboratorial, a partir da informação clínica do paciente.",
            "diferencial": "O profissional que atua nas áreas de bioquímica e uranálise, hematologia, imunologia e biologia molecular, voltado para as Análises Clínicas, necessita de aprimoramento constante frente às frequentes renovações dos métodos diagnósticos, que visam maior especificidade, sensibilidade e rapidez. A qualificação é complexa, pois envolve diferentes áreas do conhecimento técnico e também aspectos organizacionais e de gestão. Desta forma, o Curso de Aperfeiçoamento em hemato-imunodiagnóstico visa a capacitação de profissionais que atuam nesta área para que melhor possam atender às exigências do mercado.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Liderança de Alta Performance",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/adm.jpg",
            "area": "gestao",
            "publicoAlvo": "Gestores, líderes e profissionais de todas as áreas que almejam liderar e influenciar pessoas e equipes em contextos de alta performance. O curso está voltado a três públicos principais: a) líderes experientes que anseiam por novas práticas e experiências b) novos líderes que estão em sua primeira experiência e precisam de ferramentas e métodos para atuar no cotidiano c) futuros líderes que desejam se preparar para assumir novos desafios.",
            "competencias": "O curso oferece possibilidades de desenvolvimento progressivo das competências do participante na área de liderança. A partir de um olhar sistêmico para os níveis organizacionais, grupais e individuais, busca instigar e instrumentalizar os profissionais a desenvolver o conhecimento sobre si e sobre os outros, assim como desenvolver proficiência para liderar em diferentes contextos, estruturas e culturas. O mercado de trabalho sofre com a escassez de líderes competentes. O profissional egresso do curso estará apto a dar um passo adiante em sua carreira, uma vez que aperfeiçoará suas competências de liderança e ampliará o seu conhecimento a respeito do conceito da liderança, seus fundamentos e práticas. O curso propicia ao aluno avaliar em que estágio de desenvolvimento de liderança se encontra e os próximos passos para a sua atuação, por meio da construção de uma visão prática de liderança.",
            "diferencial": "Mercado de trabalho: Reflexão e ação permeiam todas as unidades curriculares do curso, alinhando conhecimento conceitual e prática do dia a dia da liderança. Processo de ensino e aprendizagem orientados a desenvolver uma visão de liderança pessoal, a desenvolver estratégias para formar excelentes equipes, gerar e mensurar resultados, desenvolver e inspirar pessoas, compreender diferentes culturas e liderar mudanças. Estrutura: Ambiente moderno, com recursos audiovisuais e configurações de sala de aula que facilitam o dinamismo das aulas. Networking: Aulas com profissionais reconhecidos no mercado, atividades que permitem conhecer e apoiar o desenvolvimento entre pares e espaço para casos pessoais serem desenvolvidos. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Psicologia e as Relações de Trabalho",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "6 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/psicologia.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com formação superior em qualquer área do conhecimento.",
            "competencias": "Ao final do curso, o profissional estará apto a analisar, atuar e propor ações no seu campo de trabalho, considerando os aspectos psicológicos.",
            "diferencial": "Correlação do que há de mais moderno no campo das neurociências ao contexto de trabalho. Enfoque no processo de envelhecimento e aposentadoria - tendência, já que o país está envelhecendo. Aulas práticas, com simulações e visitas técnicas.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Aperfeiçoamento em Psicopedagogia Institucional",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "6 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/pedagogia.jpg",
            "area": "educacao",
            "publicoAlvo": "Profissionais com formação superior em Psicologia, Pedagogia, Fonoaudiologia e licenciaturas.",
            "competencias": "O curso capacitará o aluno para atuar de forma ética, baseando-se no respeito às diferenças, à vida humana e às necessidades dos indivíduos, fazendo uso de princípios e técnicas que norteiam a ação do psicopedagogo. O curso buscará, ainda, desenvolver a capacidade de melhoria no rendimento escolar com o trabalho psicopedagógico de intervenção e prevenção de estudantes que enfrentam dificuldades de aprendizagem.",
            "diferencial": "O profissional da Psicopedagogia Institucional dedica-se ao estudo do processo de aprendizagem e sua atuação volta-se para crianças, adolescentes e adultos que apresentem dificuldades de aprendizagem no âmbito institucional. O psicopedagogo institucional pode atuar com um grupo de pessoas, em diversas situações seja em instituições de ensino, empresas ou hospitais. A estrutura da PROPEX conta com salas de aula com os recursos audiovisuais, cadeiras confortáveis, auditório, biblioteca, sala de estudos, espaço para dinâmicas e estudo de casos, além de contar com a equipe de colaboradores exclusiva para atendimento aos alunos da Pós-graduação. O corpo docente do curso é composto por profissionais especializados nas áreas das disciplinas que atuarão, orientados para o propósito de desenvolver suas aulas de forma dinâmica, apresentando o conteúdo teórico voltado para atuação prática.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Ciências do Laboratório Clínico e Diagnóstico 'In Vitro'",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "12 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/biomedicina.jpg",
            "area": "saude",
            "publicoAlvo": "Graduados em Ciências Biológicas, Farmácia, Biomedicina, Nutrição e Medicina Veterinária. Interessados em desenvolver conhecimentos e habilidades necessárias para atuação em Laboratório Clínico, assim como os profissionais de áreas afins como Medicina, Odontologia e Enfermagem.",
            "competencias": "Gerar conhecimentos teóricos e práticos referentes às técnicas diagnósticas das áreas de Microbiologia e Imunologia, Bioquímica e Urinálise, Hematologia, Parasitologia e Biologia Molecular. Fornecer ferramentas teóricas e práticas para subsidiar o gerenciamento de um laboratório de análises clínicas. Propiciar condições para uma análise interdisciplinar no diagnóstico laboratorial, a partir da informação clínica do paciente.",
            "diferencial": "O profissional que atua em Laboratório de Análises Clínicas necessita de aprimoramento constante frente às frequentes renovações dos métodos diagnósticos, que visam uma maior especificidade, sensibilidade e rapidez. A qualificação é complexa, pois envolve diferentes áreas do conhecimento técnico e também aspectos organizacionais e de gestão. Desta forma, o Curso de Especialização em Ciências do Laboratório Clínico e Diagnóstico In Vitro visa a capacitação de profissionais que atuam nesta área, para que melhor possam atender às exigências do mercado.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Direito material e processual do trabalho",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Segunda e Quarta (Semanal), Sexta (Quinzenal)",
            "duracao": "12 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/direito.jpg",
            "area": "direito",
            "publicoAlvo": "Profissionais com formação superior em Direito.",
            "competencias": "Embora o Direito do Trabalho esteja em constante transformação, o ano de 2017 foi marcado por impactantes alterações estruturais nas normas jus trabalhistas. Atenta a isso, a Especialização em Direito Material e Processual do Trabalho da Unigranrio habilita o pós-graduando para atender às novas demandas que se impõem em razão da Reforma Trabalhista. No plano do Direito Material, o curso concentra-se no estudo dos novos institutos inseridos na CLT pela Lei 13.467/17 e na sua compatibilização com os princípios fundadores do Direito do Trabalho. No âmbito do Direito Processual, o curso prepara o pós-graduando para as exigências práticas da advocacia trabalhista, tendo em vista as repercussões do Novo Código de Processo Civil e da reforma trabalhista. As disciplinas da trilha comum apresentam contornos fortemente interdisciplinares, trazendo para aplicação no Direito do Trabalho reflexões tipicamente desenvolvidas em outras ciências ou ramos do Direito.",
            "diferencial": "A Especialização em Direito Material e Processual do Trabalho da Unigranrio possui um projeto pedagógico integralmente ajustado às alterações implementadas pela reforma trabalhista. As disciplinas abordam conteúdos interdisciplinares que complementam diretamente a formação do profissional que pretende atuar no Direito do Trabalho, seja no âmbito contencioso ou em atividade consultiva de prevenção de passivos trabalhistas. O curso ainda reforça o desempenho dos interessados em concursos públicos para Magistratura do Trabalho, Ministério Público do Trabalho ou outros cargos nos Tribunais do Trabalho. Por oferecer parte das disciplinas em EaD, viabiliza-se a rápida conclusão do curso.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Enfermagem em Urgência e Emergência",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "12 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/enfermagem.jpg",
            "area": "saude",
            "publicoAlvo": "Enfermeiros que queiram se especializar no Atendimento de Emergência a pessoas com agravos de saúde no ambiente Pré e Intra-Hospitalar.",
            "competencias": "Compreender, organizar e desenvolver o processo de trabalho no contexto das situações de urgência e emergência, na perspectiva da atenção a saúde individual, familiar e da coletividade. Reconhecer as situações de urgência e emergência com os instrumentos que condicionam e/ou determinam o processo de trabalho. Atuar nas situações de urgência e emergência com embasamento teórico-prático, visão crítica e reflexiva, reconhecendo as prioridades no atendimento a indivíduo, família e comunidade.",
            "diferencial": "Utilização de manuais e protocolos atualizados junto a AHA (American Heart Association) e STN (Society Trauma for Nurses). Utilização de metodologias ativas de ensino, com foco em simulação realística em laboratório especializado.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Estética",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "12 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/estetica.jpg",
            "area": "saude",
            "publicoAlvo": "Profissionais com formação superior em estética e cosmética, biomedicina, fisioterapia e nas demais áreas afins.",
            "competencias": "Realizar procedimentos de assistência em pós-operatório facial e corporal aplicando os recursos cosméticos, manuais e eletroterápicos. Analisar as formulações cosméticas aplicando os diversos tratamentos estéticos. Selecionar os nutracêuticos apropriados, associando aos tratamentos estéticos. Construir uma visão ampla do empreendedorismo associando à Clínica Estética.",
            "diferencial": "Forte relação entre a teoria e a prática. Aulas práticas em laboratórios específicos. Grade curricular atualizada com o mercado de trabalho.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Fármacia Hospitalar e Clínica",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "12 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/farmacia.jpg",
            "area": "saude",
            "publicoAlvo": "Profissionais com Formação Superior em Farmácia.",
            "competencias": "O curso tem como objetivo desenvolver habilidades para a implementação e o gerenciamento dos serviços Farmacêuticos no âmbito Administrativo e Clínico. Interagir com a equipe multiprofissional em saúde, garantindo o uso racional de medicamento e promovendo a Farmacoeconomia. Implantar projetos e protocolos clínicos, aumentando a qualidade da assistência Farmacêutica. Compreender a complexidade das organizações hospitalares, implementar os serviços Farmacêuticos e gerenciar pessoas e processos.",
            "diferencial": "Pós-Graduação com disciplinas ministradas por profissionais qualificados e atuantes na profissão.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Finanças e Gestão Tributária",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias / Fatenp/Nova Palhoça IX",
            "diasAula": "Segunda e Quarta (Semanal), Sexta (Quinzenal) e Terça e Quinta (Semanal), Sexta (Quinzenal) / Terça e Quinta",
            "duracao": "12 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/gestao_financeira.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de gestão dos recursos financeiros e tributários como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso, o participante estará apto a desenvolver políticas de gestão financeira e controle tributário, que atendam às especificidades das organizações e do mercado.",
            "diferencial": "Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão de Marketing e Finanças",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Segunda e Quarta (Semanal), Sexta (Quinzenal) e Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses ou 12 meses",
            "horario": "08:00 às 14:00 / 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/marketing.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing e de finanças como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso o participante estará apto a compreender o mercado, planejar o composto de marketing, implantar estratégias mercadológicas, bem como entender o impacto da gestão financeira das atividades realizadas, a forma de analisar os resultados e compreender a saúde financeira da organização.",
            "diferencial": "Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão de Marketing e Logística Integrada",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Segunda a Sexta",
            "duracao": "6 meses ou 12 meses",
            "horario": "08:00 às 14:00 / 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/logistica.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing e de logística como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso o participante estará apto a compreender o mercado, planejar o composto de marketing, desenvolver e implementar estratégias mercadológicas, sendo capaz de disponibilizar adequadamente bens e serviços conforme previsto no plano de marketing.",
            "diferencial": "Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão de Pessoas e Finanças",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Segunda a Sexta",
            "duracao": "6 meses ou 12 meses",
            "horario": "08:00 às 14:00 / 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/gestao_financeira.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de gestão de pessoas e finanças como fontes de vantagens competitivas.",
            "competencias": "Ao final de curso o participante estará apto a entender a importância das práticas de recursos humanos no sucesso da organização e a sua influência nos resultados financeiros de avaliação de investimentos, retornos financeiros, fluxos de caixa e de análise de recursos utilizados pelas equipes.",
            "diferencial": "Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão de Pessoas e Logística Integrada",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Segunda a Sexta",
            "duracao": "6 meses ou 12 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/rh.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de gestão de pessoas e logística como fontes de vantagens competitivas.",
            "competencias": "Ao final do curso o participante estará apto a entender a importância das práticas de recursos humanos no sucesso da organização e a sua influência nos resultados operacionais e logísticos, promovendo a integração entre setores, processos e pessoas, motivando e empoderando as equipes na busca de resultados.",
            "diferencial": "Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão de Processos e Finanças",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "12 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/gestao_financeira.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais da área Financeira e ou Gestores nas Organizações. Necessita de formação acadêmica em Administração, Finanças, Tecnologia de Informação, Engenharia de Produção e afins, que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos Processos Organizacionais e na Gestão de Recursos Financeiros das Organizações como fonte de diferencial competitivo nas empresas.",
            "competencias": "Ao término do curso, o profissional estará apto a combinar as técnicas de gestão de processos, visando o aprimoramento da gestão de recursos da organização e de suas aplicações aos processos e gestão financeira e de aplicação de capital.",
            "diferencial": "Fazer compreender as técnicas de gestão de processos e a interação com as diversas áreas da organização, entendendo particularmente suas orientações financeiras e sua interação com a gestão de capital.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão de Processos e Logística",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "12 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/logistica.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais da área de Logística e ou gestores nas organizações. Necessita de formação acadêmica em Administração, Logística, Tecnologia de Informação, Engenharia de Produção e afins, que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos Processos Organizacionais e de Logística como fonte de diferencial competitivo.",
            "competencias": "Ao término do curso, o profissional estará apto a combinar as técnicas de Gestão de Processos, visando o aprimoramento da gestão de recursos da organização e de suas aplicações ao mercado e às atividades de marketing em geral.",
            "diferencial": "Fazer compreender as técnicas de Gestão de Processos e a interação com as diversas áreas da organização, entendendo particularmente suas orientações de fluxos e da gestão dos instrumentos de Logística.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão de Processos e Marketing",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Segunda a Sexta",
            "duracao": "6 meses e 12 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/marketing.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais da área de Marketing e ou Gestores nas Organizações. Necessita de formação acadêmica em Administração, Marketing, Tecnologia de Informação, Engenharia de Produção e afins, que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos Processos Organizacionais e de Administração de Mercado como fonte de diferencial competitivo na busca da vantagem competitiva tanto pessoal como empresarial.",
            "competencias": "Ao término do curso, o profissional estará apto a combinar as técnicas de gestão de processos, visando o aprimoramento da gestão de recursos da organização e de suas aplicações ao mercado e às atividades de marketing em geral.",
            "diferencial": "Fazer compreender as técnicas de gestão de processos e a interação com as diversas áreas da organização, entendendo particularmente suas orientações de mercado e a gestão dos instrumentos de marketing.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão de Processos e Pessoas",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Segunda e Quarta (Semanal), Sexta (Quinzenal) e Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "6 meses ou 12 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/adm.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais da área de Gestão de Pessoas e ou Gestores nas Organizações. Necessita de formação acadêmica em Administração, Recursos Humanos, Tecnologia de Informação, Engenharia de Produção e afins, que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos Processos Organizacionais e de Gestão de Recursos Humanos como fonte de diferencial competitivo na busca da vantagem competitiva tanto pessoal, como empresarial.",
            "competencias": "Ao término do curso, o profissional estará apto a combinar as técnicas de gestão de processos, visando o aprimoramento da gestão de recursos da organização e de suas interações com os processos de pessoas e a gestão do capital humano.",
            "diferencial": "Fazer compreender as técnicas de gestão de processos e a interação com as diversas áreas da organização, entendendo particularmente as interações das pessoas e a valorização do capital humano.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão Estratégica de Pessoas e Marketing",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Segunda e Quarta (Semanal), Sexta (Quinzenal)",
            "duracao": "12 meses",
            "horario": "08:00 às 14:00 / 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/rh.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing e de pessoas como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso, o participante estará apto a compreender o mercado, planejar o composto de marketing, implantar estratégias mercadológicas e entender o impacto da correta gestão de recursos humanos no que tange a liderança, proatividade e comprometimento, na aplicação das ferramentas de marketing e no sucesso da empresa.",
            "diferencial": "Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "Gestão Financeira e Logística",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "12 meses",
            "horario": "08:00 às 14:00 / 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/gestao_financeira.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de gestão de logística e finanças como fontes de vantagens competitivas.",
            "competencias": "Ao final de curso, o participante estará apto a entender a importância das práticas das atividades logísticas de planejamento de compras, produção, movimentação, entregas e logística reversa, bem como a sua influência nos resultados financeiros de avaliação de investimentos, retornos financeiros, fluxos de caixa e de análise de recursos utilizados pelas equipes.",
            "diferencial": "Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso": "MBA em Gestão Avançada",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Segunda e Quarta (Semanal), Sexta (Quinzenal) e Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "12 meses, 18 meses ou 24 meses",
            "horario": "19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "810 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/adm.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando, de forma ampla e abrangente, desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Agilidade: Conclua seu MBA em 12 meses. Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso":"MBA em Gestão Essencial com Ênfase em Marketing, Logística e Finanças",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Segunda a Sexta (Semanal) e Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "12 meses ou 18 meses",
            "horario": "08:00 às 14:00 / 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "630 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/marketing.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas. Escolhendo três das quatro áreas de conhecimento.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Agilidade: Conclua seu MBA em 12 meses. Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso":"MBA em Gestão Essencial com Ênfase em Recursos Humanos, Logística e Finanças",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Segunda a Sexta (Semanal) e Terça e Quinta (Semanal), Sexta (Quinzenal)",
            "duracao": "12 meses ou 18 meses",
            "horario": "08:00 às 14:00 / 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "630 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/gestao_financeira.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas. Escolhendo três das quatro áreas de conhecimento.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Agilidade: Conclua seu MBA em 12 meses. Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso":"MBA em Gestão Essencial com Ênfase em Recursos Humanos, Marketing e Finanças",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / ",
            "duracao": "12 meses ou 18 meses",
            "horario": "08:00 às 14:00 / ",
            "frequencia": "Semanal",
            "cargaHoraria": "630 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/adm.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas. Escolhendo três das quatro áreas de conhecimento.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Agilidade: Conclua seu MBA em 12 meses. Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal.Agilidade: Conclua seu MBA em 12 meses. Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra."
        },
        {
            "nomeCurso":"MBA em Gestão Essencial com Ênfase em Recursos Humanos, Marketing e Logística",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado / Segunda a Sexta (Semanal) e Segunda e Quarta (Semanal), Sexta (Quinzenal)",
            "duracao": "12 meses ou 18 meses",
            "horario": "08:00 às 14:00 / 19:00 às 22:00",
            "frequencia": "Semanal",
            "cargaHoraria": "630 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/rh.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas. Escolhendo três das quatro áreas de conhecimento.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Agilidade: Conclua seu MBA em 12 meses. Flexibilidade: Personalize seu curso, priorize as áreas do conhecimento de acordo com suas necessidades. Mercado de trabalho: Aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Estrutura: Ambiente moderno, com recursos audiovisuais que facilitam o dinamismo das aulas. Networking: Aulas com profissionais de mercado abordando temas atuais e tendências do mercado. Interatividade: Ambiente virtual, com conteúdo on-line e acervo com mais de 12 mil títulos na íntegra.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso":"Psicologia Organizacional",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "12 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/psicologia.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais das áreas de Gestão, Educação, Serviço Social e áreas afins que tenham o desejo de melhorar a sua performance profissional.",
            "competencias": "Ter capacidade de gerir pessoas, liderando equipes, resolvendo conflitos e respondendo aos desafios pessoais e profissionais de forma proativa e crítica, que permita buscar soluções dentro da realidade empresarial e baseado no respeito à diversidade e à ética. Dominar a comunicação com o outro, tendo a capacidade de mobilizar recursos e pessoas de diferentes contextos sociais, para agir com sinergia, participar de atividades coletivas, liderar e partilhar a liderança com o objetivo de dinamizar e garantir a consecução de metas e processos empresariais.",
            "diferencial": "O curso de Psicologia Organizacional é voltado a profissionais de empresas privadas, públicas e de economia mista que tenham interesse em melhorar a sua performance profissional dominando ferramentas para a gestão de pessoas no contexto do trabalho, a partir da Psicologia aplicada às relações humanas e ao ambiente empresarial, de técnicas de liderança, gestão de conflitos, experiências e recursos instrumentais de interesse às práticas empresariais e à consecução de metas corporativas.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        },
        {
            "nomeCurso":"Psicopedagogia Institucional e Clínica",
            "modalidade": "Presencial",
            "unidade": "RJ - Campus I - Duque de Caxias",
            "diasAula": "Sábado",
            "duracao": "12 meses",
            "horario": "08:00 às 14:00",
            "frequencia": "Semanal",
            "cargaHoraria": "450 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/pedagogia.jpg",
            "area": "educacao",
            "publicoAlvo": "Profissionais com formação superior em Psicologia, Pedagogia, Fonoaudiologia e licenciaturas.",
            "competencias": "O curso busca apresentar a atuação ética, baseada no respeito e nas diferenças individuais, fazendo uso de princípios e técnicas que norteiam a ação do psicopedagogo. Busca-se, ainda, desenvolver a capacidade de minimizar o fracasso escolar com o trabalho psicopedagógico de intervenção, prevenção e também terapêutico de estudantes que enfrentam dificuldades de aprendizagem. O profissional da psicopedagogia poderá desempenhar suas atividades em diversos ramos, dedicando-se ao estudo do processo de aprendizagem na atuação com crianças, adolescentes e adultos que apresentarem dificuldades de aprendizagem, tanto em âmbito institucional quanto em clínico.",
            "diferencial": "A estrutura física da Instituição permite que as aulas regulares sejam realizadas com o suporte didático e tecnológico necessários para a aprendizagem dos conteúdos propostos. A PROPEP conta com salas de aula equipadas com projetores, som, ar-condicionado e cadeiras confortáveis. A disciplina de atuação em cenário prático ocorrerá na Policlínica de Duque de Caxias, sob supervisão do docente responsável pela disciplina. O corpo docente é composto por profissionais que atuam na área das disciplinas que são responsáveis, sendo orientados para desenvolver suas aulas de forma dinâmica, apresentando o conteúdo teórico voltado para atuação prática.",
            "preRequisito": "Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal."
        }
    ];
// }