import { cursosEadModel } from './models/ead.model';

    export const EadCursosMock: Array <cursosEadModel> = [
        {
        "nomeCurso":"Aperfeiçoamento em Gestão de Finanças",
        "duracao":"6 meses",
        "modalidade": "EaD (Ensino à Distância)",
        "frequencia": "Semanal",
        "cargaHoraria": "180 horas",
        "titulo": "Aperfeiçoamento",
        "imagem": "http://unigranrio.com.br/_hotsite/_img/adm.jpg",
        "area": "gestao",
        "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de recursos financeiros como fonte de vantagens competitivas.",
        "competencias": "Ao final do curso, o participante estará apto a desenvolver políticas de gestão financeira que atendam às especificidades do mercado.",
        "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
        "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
        "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
        "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
        "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
        "grade1": "CONTABILIDADE FINANCEIRA, GERENCIAL E CONTROLADORIA - 30h",
        "grade2": "CONTROLES E PLANEJAMENTO TRIBUTÁRIO - 15h",
        "grade3": "DECISÕES DE FINANÇAS CORPORATIVAS - 30h",
        "grade4": "DEMONSTRATIVOS E GESTÃO DE VARIÁVEIS FINANCEIRAS - 30h",
        "grade5": "GESTÃO FINANCEIRA E GOVERNANÇA CORPORATIVA - 30h",
        "grade6": "MATEMÁTICA FINANCEIRA APLICADA - 15h",
        "grade7": "MERCADOS FINANCEIRO E DE CAPITAIS - 15h",
        "grade8": "POLÍTICAS DE GESTÃO DE RISCO E CRÉDITO - 15h",
        "grade9": "",
        "grade10": "",
        "grade11": "",
        "grade12": "",
        "grade13": "",
        "grade14": "",
        "grade15": "",
        "grade16": "",
        "grade17": "",
        "grade18": "",
        "grade19": "",
        "grade20": "",
        "grade21": "",
        "grade22": "",
        "grade23": "",
        "grade24": "",
        "grade25": "",
        "grade26": "",
        "grade27": "",
        "grade28": "",
        "grade29": "",
        "grade30": "",
        "grade31": "",
        },
        {
            "nomeCurso":"Aperfeiçoamento em Gestão de Marketing",
            "duracao":"6 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/marketing.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso, o participante estará apto a compreender o mercado, planejar o composto de marketing e a desenvolver e implementar estratégias mercadológicas, de forma a potencializar os recursos organizacionais, conforme previsto no plano de marketing.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "ESTRATÉGIA E GESTÃO DE PRODUTOS E MARCAS - 30h",
            "grade2": "ESTRATÉGIAS DE CANAIS E VENDAS - 30h",
            "grade3": "ESTRATÉGIAS DE COMUNICAÇÃO INTEGRADA - 15h",
            "grade4": "ESTRATÉGIAS DE MERCADO E COMPORTAMENTO DO CONSUMIDOR - 30h",
            "grade5": "ESTRATÉGIAS DE PRECIFICAÇÃO - 15h",
            "grade6": "FUNDAMENTOS DE MARKETING E ESTRATÉGIA DE POSICIONAMENTO - 30h",
            "grade7": "GESTÃO DE INTELIGÊNCIA DE MARKETING - 15h",
            "grade8": "GESTÃO DE VAREJO - 15h",
            "grade9": "",
            "grade10": "",
            "grade11": "",
            "grade12": "",
            "grade13": "",
            "grade14": "",
            "grade15": "",
            "grade16": "",
            "grade17": "",
            "grade18": "",
            "grade19": "",
            "grade20": "",
            "grade21": "",
            "grade22": "",
            "grade23": "",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"Aperfeiçoamento em Gestão de Pessoas",
            "duracao":"6 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "180 horas",
            "titulo": "Aperfeiçoamento",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/rh.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de capital humano como fonte de vantagens competitivas.",
            "competencias": "O participante estará apto a compreender o impacto da correta gestão de recursos humanos no que tange a liderança, proatividade e comprometimento no sucesso da empresa.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "GESTÃO CONTRATAÇÃO, RETENÇÃO E REMUNERAÇÃO - 30h",
            "grade2": "GESTÃO DE CARREIRAS - 15h",
            "grade3": "GESTÃO DE EQUIPES, MUDANÇAS E CLIMA ORGANIZACIONAL - 30h",
            "grade4": "GESTÃO DO CONHECIMENTO E EDUCAÇÃO CORPORATIVA - 30h",
            "grade5": "GESTÃO ESTRATÉGICA DE PESSOAS E CULTURA ORGANIZACIONAL - 30h",
            "grade6": "MODELOS DE COMPETÊNCIAS E LIDERANÇA - 30h",
            "grade7": "RELAÇÕES DE TRABALHO E QUALIDADE DE VIDA - 15h",
            "grade8": "",
            "grade9": "",
            "grade10": "",
            "grade11": "",
            "grade12": "",
            "grade13": "",
            "grade14": "",
            "grade15": "",
            "grade16": "",
            "grade17": "",
            "grade18": "",
            "grade19": "",
            "grade20": "",
            "grade21": "",
            "grade22": "",
            "grade23": "",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"Gestão de Marketing e Finanças",
            "duracao":"6 meses ou 12 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "360 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/marketing.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing e de finanças como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso o participante estará apto a compreender o mercado, planejar o composto de marketing, implantar estratégias mercadológicas, bem como entender o impacto da gestão financeira das atividades realizadas, a forma de analisar os resultados e compreender a saúde financeira da organização.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CONTABILIDADE FINANCEIRA, GERENCIAL E CONTROLADORIA - 30h",
            "grade2": "CONTROLES E PLANEJAMENTO TRIBUTÁRIO - 15h",
            "grade3": "DECISÕES DE FINANÇAS CORPORATIVAS - 30h",
            "grade4": "DEMONSTRATIVOS E GESTÃO DE VARIÁVEIS FINANCEIRAS - 30h",
            "grade5": "ESTRATÉGIA E GESTÃO DE PRODUTOS E MARCAS - 30h",
            "grade6": "ESTRATÉGIAS DE CANAIS E VENDAS - 30h",
            "grade7": "ESTRATÉGIAS DE COMUNICAÇÃO INTEGRADA - 15h",
            "grade8": "ESTRATÉGIAS DE MERCADO E COMPORTAMENTO DO CONSUMIDOR - 30h",
            "grade9": "ESTRATÉGIAS DE PRECIFICAÇÃO - 15h",
            "grade10": "FUNDAMENTOS DE MARKETING E ESTRATÉGIA DE POSICIONAMENTO - 30h",
            "grade11": "GESTÃO DE INTELIGÊNCIA DE MARKETING - 15h",
            "grade12": "GESTÃO DE VAREJO - 15h",
            "grade13": "GESTÃO FINANCEIRA E GOVERNANÇA CORPORATIVA - 30h",
            "grade14": "MATEMÁTICA FINANCEIRA APLICADA - 15h",
            "grade15": "MERCADOS FINANCEIRO E DE CAPITAIS - 15h",
            "grade16": "POLÍTICAS DE GESTÃO DE RISCO E CRÉDITO - 15h",
            "grade17": "",
            "grade18": "",
            "grade19": "",
            "grade20": "",
            "grade21": "",
            "grade22": "",
            "grade23": "",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"Gestão de Marketing e Logística Integrada",
            "duracao":"6 meses ou 12 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "360 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/logistica.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing e de logística como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso o participante estará apto a compreender o mercado, planejar o composto de marketing, desenvolver e implementar estratégias mercadológicas, sendo capaz de disponibilizar adequadamente bens e serviços conforme previsto no plano de marketing.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CANAIS DE DISTRIBUIÇÃO E TRANSPORTES - 30h",
            "grade2": "ESTRATÉGIA E GESTÃO DE PRODUTOS E MARCAS - 30h",
            "grade3": "ESTRATÉGIAS DE CANAIS E VENDAS - 30h",
            "grade4": "ESTRATÉGIAS DE COMUNICAÇÃO INTEGRADA - 15h",
            "grade5": "ESTRATÉGIAS DE MERCADO E COMPORTAMENTO DO CONSUMIDOR - 30h",
            "grade6": "ESTRATÉGIAS DE PRECIFICAÇÃO - 15h",
            "grade7": "FUNDAMENTOS DE MARKETING E ESTRATÉGIA DE POSICIONAMENTO - 30h",
            "grade8": "GESTÃO DE COMPRAS, ESTOQUES E ARMAZENAGEM - 30h",
            "grade9": "GESTÃO DE CUSTOS E LEGISLAÇÃO TRIBUTÁRIA NA LOGÍSTICA - 15h",
            "grade10": "GESTÃO DE INTELIGÊNCIA DE MARKETING - 15h",
            "grade11": "GESTÃO DE LOGÍSTICA INTEGRADA E SUPPLY CHAIN MANAGEMENT - 15h",
            "grade12": "GESTÃO DE VAREJO - 15h",
            "grade13": "INDICADORES DE DESEMPENHO EM LOGÍSTICA - 15h",
            "grade14": "LOGÍSTICA DE PRODUÇÃO - 30h",
            "grade15": "LOGÍSTICA INTERNACIONAL E NEGÓCIOS GLOBAIS - 15h",
            "grade16": "LOGÍSTICA REVERSA DE PÓS-VENDA E PÓS-CONSUMO (AMBIENTAL) - 30h",
            "grade17": "",
            "grade18": "",
            "grade19": "",
            "grade20": "",
            "grade21": "",
            "grade22": "",
            "grade23": "",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"Gestão de Pessoas e Finanças",
            "duracao":"6 meses ou 12 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "360 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/gestao_financeira.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de gestão de pessoas e finanças como fontes de vantagens competitivas.",
            "competencias": "Ao final de curso o participante estará apto a entender a importância das práticas de recursos humanos no sucesso da organização e a sua influência nos resultados financeiros de avaliação de investimentos, retornos financeiros, fluxos de caixa e de análise de recursos utilizados pelas equipes.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CONTABILIDADE FINANCEIRA, GERENCIAL E CONTROLADORIA - 30h",
            "grade2": "CONTROLES E PLANEJAMENTO TRIBUTÁRIO - 15h",
            "grade3": "DECISÕES DE FINANÇAS CORPORATIVAS - 30h",
            "grade4": "DEMONSTRATIVOS E GESTÃO DE VARIÁVEIS FINANCEIRAS - 30h",
            "grade5": "GESTÃO CONTRATAÇÃO, RETENÇÃO E REMUNERAÇÃO - 30h",
            "grade6": "GESTÃO DE CARREIRAS - 15h",
            "grade7": "GESTÃO DE EQUIPES, MUDANÇAS E CLIMA ORGANIZACIONAL - 30h",
            "grade8": "GESTÃO DO CONHECIMENTO E EDUCAÇÃO CORPORATIVA - 30h",
            "grade9": "GESTÃO ESTRATÉGICA DE PESSOAS E CULTURA ORGANIZACIONAL - 30h",
            "grade10": "GESTÃO FINANCEIRA E GOVERNANÇA CORPORATIVA - 30h",
            "grade11": "MATEMÁTICA FINANCEIRA APLICADA - 15h",
            "grade12": "MERCADOS FINANCEIRO E DE CAPITAIS - 15h",
            "grade13": "MODELOS DE COMPETÊNCIAS E LIDERANÇA - 30h",
            "grade14": "POLÍTICAS DE GESTÃO DE RISCO E CRÉDITO - 15h",
            "grade15": "RELAÇÕES DE TRABALHO E QUALIDADE DE VIDA - 15h",
            "grade16": "",
            "grade17": "",
            "grade18": "",
            "grade19": "",
            "grade20": "",
            "grade21": "",
            "grade22": "",
            "grade23": "",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"Gestão de Pessoas e Logística Integrada",
            "duracao":"6 meses ou 12 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "360 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/rh.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de gestão de pessoas e logística como fontes de vantagens competitivas.",
            "competencias": "Ao final do curso o participante estará apto a entender a importância das práticas de recursos humanos no sucesso da organização e a sua influência nos resultados operacionais e logísticos, promovendo a integração entre setores, processos e pessoas, motivando e empoderando as equipes na busca de resultados.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CANAIS DE DISTRIBUIÇÃO E TRANSPORTES - 30h",
            "grade2": "GESTÃO CONTRATAÇÃO, RETENÇÃO E REMUNERAÇÃO - 30h",
            "grade3": "GESTÃO DE CARREIRAS - 15h",
            "grade4": "GESTÃO DE COMPRAS, ESTOQUES E ARMAZENAGEM - 30h",
            "grade5": "GESTÃO DE CUSTOS E LEGISLAÇÃO TRIBUTÁRIA NA LOGÍSTICA - 15h",
            "grade6": "GESTÃO DE EQUIPES, MUDANÇAS E CLIMA ORGANIZACIONAL - 30h",
            "grade7": "GESTÃO DE LOGÍSTICA INTEGRADA E SUPPLY CHAIN MANAGEMENT - 15h",
            "grade8": "GESTÃO DO CONHECIMENTO E EDUCAÇÃO CORPORATIVA - 30h",
            "grade9": "GESTÃO ESTRATÉGICA DE PESSOAS E CULTURA ORGANIZACIONAL - 30h",
            "grade10": "INDICADORES DE DESEMPENHO EM LOGÍSTICA - 15h",
            "grade11": "LOGÍSTICA DE PRODUÇÃO - 30h",
            "grade12": "LOGÍSTICA INTERNACIONAL E NEGÓCIOS GLOBAIS - 15h",
            "grade13": "LOGÍSTICA REVERSA DE PÓS-VENDA E PÓS-CONSUMO (AMBIENTAL) - 30h",
            "grade14": "MODELOS DE COMPETÊNCIAS E LIDERANÇA - 30h",
            "grade15": "RELAÇÕES DE TRABALHO E QUALIDADE DE VIDA - 15h",
            "grade16": "",
            "grade17": "",
            "grade18": "",
            "grade19": "",
            "grade20": "",
            "grade21": "",
            "grade22": "",
            "grade23": "",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"Gestão Estratégica de Pessoas e Marketing",
            "duracao":"12 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "360 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/rh.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing e de pessoas como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso, o participante estará apto a compreender o mercado, planejar o composto de marketing, implantar estratégias mercadológicas e entender o impacto da correta gestão de recursos humanos no que tange a liderança, proatividade e comprometimento, na aplicação das ferramentas de marketing e no sucesso da empresa.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "ESTRATÉGIA E GESTÃO DE PRODUTOS E MARCAS - 30h",
            "grade2": "ESTRATÉGIAS DE CANAIS E VENDAS - 30h",
            "grade3": "ESTRATÉGIAS DE COMUNICAÇÃO INTEGRADA - 15h",
            "grade4": "ESTRATÉGIAS DE MERCADO E COMPORTAMENTO DO CONSUMIDOR - 30h",
            "grade5": "ESTRATÉGIAS DE PRECIFICAÇÃO - 15h",
            "grade6": "FUNDAMENTOS DE MARKETING E ESTRATÉGIA DE POSICIONAMENTO - 30h",
            "grade7": "GESTÃO CONTRATAÇÃO, RETENÇÃO E REMUNERAÇÃO - 30h",
            "grade8": "GESTÃO DE CARREIRAS - 15h",
            "grade9": "GESTÃO DE EQUIPES, MUDANÇAS E CLIMA ORGANIZACIONAL - 30h",
            "grade10": "GESTÃO DE INTELIGÊNCIA DE MARKETING - 15h",
            "grade11": "GESTÃO DE VAREJO - 15h",
            "grade12": "GESTÃO DO CONHECIMENTO E EDUCAÇÃO CORPORATIVA - 30h",
            "grade13": "GESTÃO ESTRATÉGICA DE PESSOAS E CULTURA ORGANIZACIONAL - 30h",
            "grade14": "MODELOS DE COMPETÊNCIAS E LIDERANÇA - 30h",
            "grade15": "RELAÇÕES DE TRABALHO E QUALIDADE DE VIDA - 15h",
            "grade16": "",
            "grade17": "",
            "grade18": "",
            "grade19": "",
            "grade20": "",
            "grade21": "",
            "grade22": "",
            "grade23": "",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"Gestão Financeira e Logística",
            "duracao":"6 meses ou 12 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "360 horas",
            "titulo": "Especialização",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/gestao_financeira.jpg",
            "area": "gestao",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de gestão de logística e finanças como fontes de vantagens competitivas.",
            "competencias": "Ao final de curso, o participante estará apto a entender a importância das práticas das atividades logísticas de planejamento de compras, produção, movimentação, entregas e logística reversa, bem como a sua influência nos resultados financeiros de avaliação de investimentos, retornos financeiros, fluxos de caixa e de análise de recursos utilizados pelas equipes.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CANAIS DE DISTRIBUIÇÃO E TRANSPORTES - 30h",
            "grade2": "CONTABILIDADE FINANCEIRA, GERENCIAL E CONTROLADORIA - 30h",
            "grade3": "CONTROLES E PLANEJAMENTO TRIBUTÁRIO - 15h",
            "grade4": "DECISÕES DE FINANÇAS CORPORATIVAS - 30h",
            "grade5": "DEMONSTRATIVOS E GESTÃO DE VARIÁVEIS FINANCEIRAS - 30h",
            "grade6": "GESTÃO DE COMPRAS, ESTOQUES E ARMAZENAGEM - 30h",
            "grade7": "GESTÃO DE CUSTOS E LEGISLAÇÃO TRIBUTÁRIA NA LOGÍSTICA - 15h",
            "grade8": "GESTÃO DE LOGÍSTICA INTEGRADA E SUPPLY CHAIN MANAGEMENT - 15h",
            "grade9": "GESTÃO FINANCEIRA E GOVERNANÇA CORPORATIVA - 30h",
            "grade10": "INDICADORES DE DESEMPENHO EM LOGÍSTICA - 15h",
            "grade11": "LOGÍSTICA DE PRODUÇÃO - 30h",
            "grade12": "LOGÍSTICA INTERNACIONAL E NEGÓCIOS GLOBAIS - 15h",
            "grade13": "LOGÍSTICA REVERSA DE PÓS-VENDA E PÓS-CONSUMO (AMBIENTAL) - 30h",
            "grade14": "MATEMÁTICA FINANCEIRA APLICADA - 15h",
            "grade15": "MERCADOS FINANCEIRO E DE CAPITAIS - 15h",
            "grade16": "POLÍTICAS DE GESTÃO DE RISCO E CRÉDITO - 15h",
            "grade17": "",
            "grade18": "",
            "grade19": "",
            "grade20": "",
            "grade21": "",
            "grade22": "",
            "grade23": "",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"MBA em Gestão Avançada",
            "duracao":"12 meses, 18 meses ou 24 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "720 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/adm.jpg",
            "area": "mba",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando, de forma ampla e abrangente, desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CANAIS DE DISTRIBUIÇÃO E TRANSPORTES - 30h",
            "grade2": "CONTABILIDADE FINANCEIRA, GERENCIAL E CONTROLADORIA - 30h",
            "grade3": "CONTROLES E PLANEJAMENTO TRIBUTÁRIO - 15h",
            "grade4": "DECISÕES DE FINANÇAS CORPORATIVAS - 30h",
            "grade5": "DEMONSTRATIVOS E GESTÃO DE VARIÁVEIS FINANCEIRAS - 30h",
            "grade6": "ESTRATÉGIA E GESTÃO DE PRODUTOS E MARCAS - 30h",
            "grade7": "ESTRATÉGIAS DE CANAIS E VENDAS - 30h",
            "grade8": "ESTRATÉGIAS DE COMUNICAÇÃO INTEGRADA - 15h",
            "grade9": "ESTRATÉGIAS DE MERCADO E COMPORTAMENTO DO CONSUMIDOR - 30h",
            "grade10": "ESTRATÉGIAS DE PRECIFICAÇÃO - 15h",
            "grade11": "FUNDAMENTOS DE MARKETING E ESTRATÉGIA DE POSICIONAMENTO - 30h",
            "grade12": "GESTÃO CONTRATAÇÃO, RETENÇÃO E REMUNERAÇÃO - 30h",
            "grade13": "GESTÃO DE CARREIRAS - 15h",
            "grade14": "GESTÃO DE COMPRAS, ESTOQUES E ARMAZENAGEM - 30h",
            "grade15": "GESTÃO DE CUSTOS E LEGISLAÇÃO TRIBUTÁRIA NA LOGÍSTICA - 15h",
            "grade16": "GESTÃO DE EQUIPES, MUDANÇAS E CLIMA ORGANIZACIONAL - 30h",
            "grade17": "GESTÃO DE INTELIGÊNCIA DE MARKETING - 15h",
            "grade18": "GESTÃO DE LOGÍSTICA INTEGRADA E SUPPLY CHAIN MANAGEMENT - 15h",
            "grade19": "GESTÃO DE VAREJO - 15h",
            "grade20": "GESTÃO DO CONHECIMENTO E EDUCAÇÃO CORPORATIVA - 30h",
            "grade21": "GESTÃO ESTRATÉGICA DE PESSOAS E CULTURA ORGANIZACIONAL - 30h",
            "grade22": "GESTÃO FINANCEIRA E GOVERNANÇA CORPORATIVA - 30h",
            "grade23": "INDICADORES DE DESEMPENHO EM LOGÍSTICA - 15h",
            "grade24": "LOGÍSTICA DE PRODUÇÃO - 30h",
            "grade25": "LOGÍSTICA INTERNACIONAL E NEGÓCIOS GLOBAIS - 15h",
            "grade26": "LOGÍSTICA REVERSA DE PÓS-VENDA E PÓS-CONSUMO (AMBIENTAL) - 30h",
            "grade27": "MATEMÁTICA FINANCEIRA APLICADA - 15h",
            "grade28": "MERCADOS FINANCEIRO E DE CAPITAIS - 15h",
            "grade29": "MODELOS DE COMPETÊNCIAS E LIDERANÇA - 30h",
            "grade30": "POLÍTICAS DE GESTÃO DE RISCO E CRÉDITO - 15h",
            "grade31": "RELAÇÕES DE TRABALHO E QUALIDADE DE VIDA - 15h",
        },
        {
            "nomeCurso":"MBA em Gestão Essencial com Ênfase em Marketing, Logística e Finanças",
            "duracao":"12 meses ou 18 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "540 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/marketing.jpg",
            "area": "mba",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas. Escolhendo três das quatro áreas de conhecimento.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CANAIS DE DISTRIBUIÇÃO E TRANSPORTES - 30h",
            "grade2": "CONTABILIDADE FINANCEIRA, GERENCIAL E CONTROLADORIA - 30h",
            "grade3": "CONTROLES E PLANEJAMENTO TRIBUTÁRIO - 15h",
            "grade4": "DECISÕES DE FINANÇAS CORPORATIVAS - 30h",
            "grade5": "DEMONSTRATIVOS E GESTÃO DE VARIÁVEIS FINANCEIRAS - 30h",
            "grade6": "ESTRATÉGIA E GESTÃO DE PRODUTOS E MARCAS - 30h",
            "grade7": "ESTRATÉGIAS DE CANAIS E VENDAS - 30h",
            "grade8": "ESTRATÉGIAS DE COMUNICAÇÃO INTEGRADA - 15h",
            "grade9": "ESTRATÉGIAS DE MERCADO E COMPORTAMENTO DO CONSUMIDOR - 30h",
            "grade10": "ESTRATÉGIAS DE PRECIFICAÇÃO - 15h",
            "grade11": "FUNDAMENTOS DE MARKETING E ESTRATÉGIA DE POSICIONAMENTO - 30h",
            "grade12": "GESTÃO DE COMPRAS, ESTOQUES E ARMAZENAGEM - 30h",
            "grade13": "GESTÃO DE CUSTOS E LEGISLAÇÃO TRIBUTÁRIA NA LOGÍSTICA - 15h",
            "grade14": "GESTÃO DE INTELIGÊNCIA DE MARKETING - 15h",
            "grade15": "GESTÃO DE LOGÍSTICA INTEGRADA E SUPPLY CHAIN MANAGEMENT - 15h",
            "grade16": "GESTÃO DE VAREJO - 15h",
            "grade17": "GESTÃO FINANCEIRA E GOVERNANÇA CORPORATIVA - 30h",
            "grade18": "INDICADORES DE DESEMPENHO EM LOGÍSTICA - 15h",
            "grade19": "LOGÍSTICA DE PRODUÇÃO - 30h",
            "grade20": "LOGÍSTICA INTERNACIONAL E NEGÓCIOS GLOBAIS - 15h",
            "grade21": "LOGÍSTICA REVERSA DE PÓS-VENDA E PÓS-CONSUMO (AMBIENTAL) - 30h",
            "grade22": "MATEMÁTICA FINANCEIRA APLICADA - 15h",
            "grade23": "MERCADOS FINANCEIRO E DE CAPITAIS - 15h",
            "grade24": "POLÍTICAS DE GESTÃO DE RISCO E CRÉDITO - 15h",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"MBA em Gestão Essencial com Ênfase em Recursos Humanos, Logística e Finanças",
            "duracao":"12 meses ou 18 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "540 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/gestao_financeira.jpg",
            "area": "mba",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas. Escolhendo três das quatro áreas de conhecimento.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CANAIS DE DISTRIBUIÇÃO E TRANSPORTES - 30h",
            "grade2": "CONTABILIDADE FINANCEIRA, GERENCIAL E CONTROLADORIA - 30h",
            "grade3": "CONTROLES E PLANEJAMENTO TRIBUTÁRIO - 15h",
            "grade4": "DECISÕES DE FINANÇAS CORPORATIVAS - 30h",
            "grade5": "DEMONSTRATIVOS E GESTÃO DE VARIÁVEIS FINANCEIRAS - 30h",
            "grade6": "GESTÃO CONTRATAÇÃO, RETENÇÃO E REMUNERAÇÃO - 30h",
            "grade7": "GESTÃO DE CARREIRAS - 15h",
            "grade8": "GESTÃO DE COMPRAS, ESTOQUES E ARMAZENAGEM - 30h",
            "grade9": "GESTÃO DE CUSTOS E LEGISLAÇÃO TRIBUTÁRIA NA LOGÍSTICA - 15h",
            "grade10": "GESTÃO DE EQUIPES, MUDANÇAS E CLIMA ORGANIZACIONAL - 30h",
            "grade11": "GESTÃO DE LOGÍSTICA INTEGRADA E SUPPLY CHAIN MANAGEMENT - 15h",
            "grade12": "GESTÃO DO CONHECIMENTO E EDUCAÇÃO CORPORATIVA - 30h",
            "grade13": "GESTÃO ESTRATÉGICA DE PESSOAS E CULTURA ORGANIZACIONAL - 30h",
            "grade14": "GESTÃO FINANCEIRA E GOVERNANÇA CORPORATIVA - 30h",
            "grade15": "INDICADORES DE DESEMPENHO EM LOGÍSTICA - 15h",
            "grade16": "LOGÍSTICA DE PRODUÇÃO - 30h",
            "grade17": "LOGÍSTICA INTERNACIONAL E NEGÓCIOS GLOBAIS - 15h",
            "grade18": "LOGÍSTICA REVERSA DE PÓS-VENDA E PÓS-CONSUMO (AMBIENTAL) - 30h",
            "grade19": "MATEMÁTICA FINANCEIRA APLICADA - 15h",
            "grade20": "MERCADOS FINANCEIRO E DE CAPITAIS - 15h",
            "grade21": "MODELOS DE COMPETÊNCIAS E LIDERANÇA - 30h",
            "grade22": "POLÍTICAS DE GESTÃO DE RISCO E CRÉDITO - 15h",
            "grade23": "RELAÇÕES DE TRABALHO E QUALIDADE DE VIDA - 15h",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"MBA em Gestão Essencial com Ênfase em Recursos Humanos, Marketing e Finanças",
            "duracao":"12 meses ou 18 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "540 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/adm.jpg",
            "area": "mba",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas. Escolhendo três das quatro áreas de conhecimento.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CONTABILIDADE FINANCEIRA, GERENCIAL E CONTROLADORIA - 30h",
            "grade2": "CONTROLES E PLANEJAMENTO TRIBUTÁRIO - 15h",
            "grade3": "DECISÕES DE FINANÇAS CORPORATIVAS - 30h",
            "grade4": "DEMONSTRATIVOS E GESTÃO DE VARIÁVEIS FINANCEIRAS - 30h",
            "grade5": "ESTRATÉGIA E GESTÃO DE PRODUTOS E MARCAS - 30h",
            "grade6": "ESTRATÉGIAS DE CANAIS E VENDAS - 30h",
            "grade7": "ESTRATÉGIAS DE COMUNICAÇÃO INTEGRADA - 15h",
            "grade8": "ESTRATÉGIAS DE MERCADO E COMPORTAMENTO DO CONSUMIDOR - 30h",
            "grade9": "ESTRATÉGIAS DE PRECIFICAÇÃO - 15h",
            "grade10": "FUNDAMENTOS DE MARKETING E ESTRATÉGIA DE POSICIONAMENTO - 30h",
            "grade11": "GESTÃO CONTRATAÇÃO, RETENÇÃO E REMUNERAÇÃO - 30h",
            "grade12": "GESTÃO DE CARREIRAS - 15h",
            "grade13": "GESTÃO DE EQUIPES, MUDANÇAS E CLIMA ORGANIZACIONAL - 30h",
            "grade14": "GESTÃO DE INTELIGÊNCIA DE MARKETING - 15h",
            "grade15": "GESTÃO DE VAREJO - 15h",
            "grade16": "GESTÃO DO CONHECIMENTO E EDUCAÇÃO CORPORATIVA - 30h",
            "grade17": "GESTÃO ESTRATÉGICA DE PESSOAS E CULTURA ORGANIZACIONAL - 30h",
            "grade18": "GESTÃO FINANCEIRA E GOVERNANÇA CORPORATIVA - 30h",
            "grade19": "MATEMÁTICA FINANCEIRA APLICADA - 15h",
            "grade20": "MERCADOS FINANCEIRO E DE CAPITAIS - 15h",
            "grade21": "MODELOS DE COMPETÊNCIAS E LIDERANÇA - 30h",
            "grade22": "POLÍTICAS DE GESTÃO DE RISCO E CRÉDITO - 15h",
            "grade23": "RELAÇÕES DE TRABALHO E QUALIDADE DE VIDA - 15h",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
        {
            "nomeCurso":"MBA em Gestão Essencial com Ênfase em Recursos Humanos, Marketing e Logística",
            "duracao":"12 meses ou 18 meses",
            "modalidade": "EaD (Ensino à Distância)",
            "frequencia": "Semanal",
            "cargaHoraria": "540 horas",
            "titulo": "MBA",
            "imagem": "http://unigranrio.com.br/_hotsite/_img/rh.jpg",
            "area": "mba",
            "publicoAlvo": "Profissionais com experiência e formação acadêmica, que atuam nas organizações e que estejam buscando evolução por meio do aprimoramento conceitual e da prática dos processos de marketing, pessoas, logística e finanças como fonte de vantagens competitivas. Escolhendo três das quatro áreas de conhecimento.",
            "competencias": "Ao final do curso, o aluno estará apto a entender e aplicar os modelos de gestão das empresas considerando desde a análise e posicionamento de mercado, sua forma de atendimento ao consumidor, seu processo de produção e movimentação de produtos e serviços, sua gestão de recursos financeiros e apuração de resultados, bem como o processo de envolvimento das pessoas na gestão dos recursos e na motivação para a busca de resultados.",
            "diferencial": "Mercado de trabalho: aprendizagem fundamentada em conceitos aplicáveis à sua realidade (profissional e social), consolidando seus conhecimentos e, ao mesmo tempo, melhorando sua competitividade. Conteúdos e atividades: elaborados e organizados por professores mestres e doutores na área do curso e momentos síncronos (webconferências) com profissionais especialistas nos temas atuais e tendências do mercado. Mediação: será realizado por especialistas, mestres ou doutores na área. Facilidade e comodidade: o aluno não precisa sair de casa para fazer a matrícula, entregar documentos e nem realizar a avaliação presencial. Biblioteca: acervo digital com mais de 20 mil livros. Acompanhamento dos alunos: equipe dedicada na sede para acompanhar o processo de estudo dos alunos.",
            "metodologia": "O processo de ensino-aprendizagem é considerado o centro do processo, tendo como elementos e pilares: alunos, professores, metodologias ativas, recursos didáticos e atividades significativas. Conteúdos e atividades escritos e organizados por mestres e doutores da área e com experiência docente e em elaboração de materiais didáticos para EAD. Cada disciplina possui roteiro de estudos, textos, artigos, videoaulas, estudos de caso, situações problemas e momentos síncronos de webconferência com professores convidados. O processo de mediação docente será realizado por um professor tutor, especialista, mestre ou doutor na área de conhecimento da disciplina e com experiência docente. Em cada disciplina, professores ou profissionais de mercado serão convidados para a participação nas webconferências.",
            "avaliacao": "Os instrumentos de avaliação da aprendizagem serão todos on-line e a distância. Não é necessário ir ao polo presencial. No entanto, há diferentes instrumentos de avaliação para cada uma das disciplinas – estudos de caso, fóruns de discussão, atividades em grupo, atividades individuais, atividades objetivas e de pesquisa. Este curso não terá TCC, conforme legislação vigente.",
            "organizacao": "Cada disciplina terá um cronograma de estudos e um calendário de entregas das avaliações e das webconferências (momentos síncronos). Siga as orientações postadas em cada disciplina e dedique-se conforme sugerido a você. Os momentos de webconferência ocorrerão semanalmente (conferir dias e horários no cronograma de estudos).",
            "preRequisito": "1. Diploma de Ensino Superior reconhecido pelo Ministério da Educação do Brasil ou revalidado, quando emitido em instituições de ensino estrangeiras, na forma da regulação federal. 2. Acesso à internet e kit multimídia para assistir e interagir nas webconferências, bem como para acessar a sala virtual de cada disciplina no ambiente virtual de aprendizagem.",
            "grade1": "CANAIS DE DISTRIBUIÇÃO E TRANSPORTES - 30h",
            "grade2": "ESTRATÉGIA E GESTÃO DE PRODUTOS E MARCAS - 30h",
            "grade3": "ESTRATÉGIAS DE CANAIS E VENDAS - 30h",
            "grade4": "ESTRATÉGIAS DE COMUNICAÇÃO INTEGRADA - 15h",
            "grade5": "ESTRATÉGIAS DE MERCADO E COMPORTAMENTO DO CONSUMIDOR - 30h",
            "grade6": "ESTRATÉGIAS DE PRECIFICAÇÃO - 15h",
            "grade7": "FUNDAMENTOS DE MARKETING E ESTRATÉGIA DE POSICIONAMENTO - 30h",
            "grade8": "GESTÃO CONTRATAÇÃO, RETENÇÃO E REMUNERAÇÃO - 30h",
            "grade9": "GESTÃO DE CARREIRAS - 15h",
            "grade10": "GESTÃO DE COMPRAS, ESTOQUES E ARMAZENAGEM - 30h",
            "grade11": "GESTÃO DE CUSTOS E LEGISLAÇÃO TRIBUTÁRIA NA LOGÍSTICA - 15h",
            "grade12": "GESTÃO DE EQUIPES, MUDANÇAS E CLIMA ORGANIZACIONAL - 30h",
            "grade13": "GESTÃO DE INTELIGÊNCIA DE MARKETING - 15h",
            "grade14": "GESTÃO DE LOGÍSTICA INTEGRADA E SUPPLY CHAIN MANAGEMENT - 15h",
            "grade15": "GESTÃO DE VAREJO - 15h",
            "grade16": "GESTÃO DO CONHECIMENTO E EDUCAÇÃO CORPORATIVA - 30h",
            "grade17": "GESTÃO ESTRATÉGICA DE PESSOAS E CULTURA ORGANIZACIONAL - 30h",
            "grade18": "INDICADORES DE DESEMPENHO EM LOGÍSTICA - 15h",
            "grade19": "LOGÍSTICA DE PRODUÇÃO - 30h",
            "grade20": "LOGÍSTICA INTERNACIONAL E NEGÓCIOS GLOBAIS - 15h",
            "grade21": "LOGÍSTICA REVERSA DE PÓS-VENDA E PÓS-CONSUMO (AMBIENTAL) - 30h",
            "grade22": "MODELOS DE COMPETÊNCIAS E LIDERANÇA - 30h",
            "grade23": "RELAÇÕES DE TRABALHO E QUALIDADE DE VIDA - 15h",
            "grade24": "",
            "grade25": "",
            "grade26": "",
            "grade27": "",
            "grade28": "",
            "grade29": "",
            "grade30": "",
            "grade31": "",
        },
    
    ];
