export class CursosAtualizacao {
    data: Array <any> = [
        {
            "titulo": "Espanhol básico I",
            "horario": "9h às 12h",
            "periodicidade": "Semanal (Sábado)",
            "cargaHoraria": "45 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Público em geral.",
            "beneficios": "É objetivo deste curso desenvolver em nível básico, as quatro macro-habilidades linguísticas fundamentais: expressão oral, expressão escrita, compreensão auditiva e compreensão de leitura que o aluno deverá adquirir, desenvolver e aplicar de forma sistemática e progressiva, com o auxilio de recursos multimídia e metodologias ativas de aprendizagem, que estimulem a participação do aluno como protagonista e interlocutor. Além do mais, o espanhol é uma língua falada oficialmente em 20 países e ainda nos Estados Unidos de América, onde há uma comunidade considerável de hispano falantes. Os alunos seriam diretamente beneficiados com o desenvolvimento das quatro macro-habilidades linguísticas mencionadas.",
            "area": "educacao e humanas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/10/espanhol-basico.jpg"
        },
        {
            "titulo": "Inglês para apresentações acadêmicas",
            "horario": "08h às 12h",
            "periodicidade": "Semanal (Sábado)",
            "cargaHoraria": "16 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Graduandos ou graduados em Letras, Pedagogia, História, Ciências Humanas, Tecnologia e Saúde com nível intermediário alto ou avançado de língua inglesa que precisam realizar apresentações em atividades ou eventos acadêmicos em língua inglesa.",
            "beneficios": "Apresentações em inglês são importantes e muitas vezes podem ser um diferencial para fins acadêmicos e também profissionais. No entanto, mesmo estudantes e profissionais com nível avançado de língua inglesa precisam desenvolver estratégias direcionadas para o planejamento de uma apresentação, bem como compreender características específicas da linguagem acadêmica, que incluem vocabulário, collocation, orações frequentes e como elaborar os slides da apresentação.",
            "area": "educacao e humanas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/11/ingles-apresentacao-academica.jpg"
        },
        {
            "titulo": "Práticas teatrais",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Pessoas interessadas tanto em Artes Cênicas quanto em desenvolver oratória e sua desenvoltura em aulas, reuniões e apresentações em geral para diversos públicos.",
            "beneficios": "O aluno obterá conhecimentos práticos e técnicos que o farão entender formas de se colocar em cena, bem como construir uma cena teatral, além de auxiliar no processo de auto-gestão, capacidade de trabalhar em grupo, desenvolvimento de oratória e expressão corporal para reuniões, aulas e apresentações em público.",
            "area": "educacao e humanas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/07/dreamstime_xxl_135514753.jpg"
        },
        {
            "titulo": "Neurociência Cognitiva: Como se aprende?",
            "horario": "9h às 12h",
            "periodicidade": "Semanal (Sábado)",
            "cargaHoraria": "9 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Graduados e graduandos interessados em se atualizarem na temática.",
            "beneficios": "Como será que se aprende? O que acontece no cérebro durante o processo de aprendizagem? Existe diferença entre decorar e aprender? Este curso se propõe a discutir aspectos neurocognitivos, ou seja, como aprendizagem ocorre, além de disponibilizar novidades a respeito deste tema.",
            "area": "educacao e humanas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_132829448.jpg"
        },
        {
            "titulo": "A experimentação com materiais de baixo custo no ensino de Ciências",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Licenciados e Licenciandos em Física ou Ciências.",
            "beneficios": "Complementação curricular.",
            "area": "educacao e humanas",
            "imagem":"http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_107299848.jpg"
        },
        {
            "titulo": "Ateliê dos professores dinamizadores – Leitura e literatura",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "12 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos do curso de Pedagogia e professores da Educação Básica: Educação Infantil e/ou primeiro ao quinto ano do Ensino Fundamental de rede pública e/ou particular de ensino.",
            "beneficios": "Sabemos que, a partir de um olhar contemporâneo, refletir sobre a importância de despertar o interesse do pequeno leitor através de diferentes perspectivas é fundamental na Educação Básica. Para além dessa questão, a proposta visa a formação continuada de dinamizadores de leitura e literatura das escolas públicas e privadas, e ainda, qualificar alunos(as) do curso de Pedagogia, entendendo que profissionais da área de Educação necessitam de permanente atualização. Vem contribuir para o estímulo e motivação à leitura, à literatura e à escrita. Evidencia a leitura literária como caminho para a formação do sujeito leitor.",
            "area": "educacao e humanas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_85878448.jpg"
        },
        {
            "titulo": "Atualização em legislação do SUS – Concursos, residência, ENADE e SUSEME",
            "horario": "8h às 14h",
            "periodicidade": "Quinzenal(Sábado)",
            "cargaHoraria": "24 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Alunos de graduação dos cursos de medicina, odontologia, enfermagem, farmácia e nutrição. Profissionais graduados nas áreas citadas e demais profissionais da área da saúde que buscam aprovação em concurso público ou residência.",
            "beneficios": "O tema legislação do sus tem sido um tema muito cobrado e fator determinante de aprovações em concursos na área da saúde, em provas de residência multiprofissional em saúde e provas de estágios remunerados como SUSEME.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/10/atualizacao-legislacao-sus.jpg"
        },
        {
            "titulo": "Atualização em cirurgia oral",
            "horario": "18h às 22h",
            "periodicidade": "Semanal (quartas-feiras)",
            "cargaHoraria": "96 horas",
            "unidade": "Barra da Tijuca",
            "publicoAlvo": "Graduandos do último ano do Curso de Odontologia (registrado pelo MEC) e Cirurgiões-dentistas interessados em aprofundar suas técnicas de Cirurgias Orais.",
            "beneficios": "Os alunos praticarão cirurgias orais por meio de técnicas seguras e eficientes quanto ao preparo pré-operatório do paciente, na elaboração de diagnósticos, no planejamento e realização de procedimentos odontológicos cirúrgicos. Durante o curso teremos ainda realizações de biópsias para diagnósticos patológicos orais e ambientação em Centro Cirúrgico.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/09/shutterstock_1210141582.jpg"
        },
        {
            "titulo": "Introduação à psicologia do luto",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Estudantes e profissionais da área da saúde.",
            "beneficios": "Conhecer sobre luto desde a conceituação e fundamentação teórica às estratégias de intervenção. Desmistificação dos tipos específicos de luto e seu manejo. O luto da criança, do adulto e dos idosos, além da perspectiva de gênero e das condições especiais de saúde.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/09/shutterstock_742060153.jpg"
        },
        {
            "titulo": "Exclusão de paternidade e identificação de pessoas: A genética utilizada na Ciência Forense",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Estudantes de graduação de biologia, biomedicina, direito ou cursos afins, interessados na área de Perícia Forense.",
            "beneficios": "Apresenta princípios básicos do uso da Genética Forense na exclusão de paternidade e identificação de pessoas.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/08/shutterstock_691546417.jpg"
        },
        {
            "titulo": "Atualização em hipnose clínica para odontologia",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "32 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Acadêmicos de Odontologia e Cirurgiões-Dentistas com o desejo de conhecer as técnicas de hipnose utilizadas na Odontologia.",
            "beneficios": "A hipnose é uma ferramenta importante para o manejo de pacientes fóbicos, acometidos por fobia dental e pacientes portadores de dor crônica. O curso visa o preparo do Cirurgião-Dentista para o manejo desses pacientes. O aluno aprenderá os principais conceitos da Hipnose Clínica e sua aplicabilidade no atendimento odontológico.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/08/shutterstock_795332008.jpg"
        },
        {
            "titulo": "Yoga",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos das áreas de Educação Física e Fisioterapia, praticantes e instrutores de Yoga.",
            "beneficios": "Apresentar o Yoga – História e filosofia das antigas escrituras Indianas “O Yoga Sutra”. Os estilos do hatha Yoga, os corpos energéticos e os chakras, aspectos físicos e respiratórios relacionados aos mesmos, as formas de trabalhar os asanas (posturas físicas) e pranayamas (exercícios respiratórios).",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_44510334.jpg"
        },
        {
            "titulo": "Atualização em tratamento endodôntico em molares – Avançado",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "44 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados ou Graduandos do curso de Odontologia, que já tenham cursado com aprovação a disciplina de Endodontia II e profissionais formados no curso superior de Odontologia em instituição de ensino reconhecida pelo MEC e que tenha que tenham cursado obrigatoriamente o curso de Aperfeiçoamento em Tratamento Endodôntico em Molares.",
            "beneficios": "Enfoque no diagnóstico endodôntico para a aplicação dos conteúdos empoderados no curso de Aperfeiçoamento de Tratamento Endodôntico de Molares em atendimento clínico a pacientes com necessidades endodônticas.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_104000101.jpg"
        },
        {
            "titulo": "Medicação aplicada à enfermagem",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Alunos do curso de graduação em enfermagem tendo cursado a disciplina de Farmacologia, enfermeiros e técnicos de enfermagem.",
            "beneficios": "O curso destina se a habilitar profissionais de enfermagem no preparo, diluição, administração e cálculo de medicamentos e técnicas de punção venosa. A fundamentação de técnicos de enfermagem e enfermeiros, no que tange o contexto de boas práticas deste procedimento tão habitual na rotina hospitalar, possibilita a redução e controle dos indicadores de infecções.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_105529456-edit.jpg"
        },
        {
            "titulo": "Suporte básico de vida (BLS) – Adulto",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos de Enfermagem, além de enfermeiros e técnicos de enfermagem.",
            "beneficios": "O curso destina-se a habilitar profissionais de enfermagem no atendimento emergencial a vítima de parada cardio respiratória em situações pré e intra hospitalar, com base nas diretrizes da Amerincan Heart.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_70396617-menor.jpg"
        },
        {
            "titulo": "Cariologia: da teoria à prática clínica",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "36 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e Graduandos de Odontologia à partir do sexto período e Cirurgiões-dentistas.",
            "beneficios": "O objetivo do curso é o aprimoramento dos conceitos teóricos básicos de cariologia na prática clínica. Tornar-se-ão profissionais capacitados para diagnosticar, planejar e executar tratamento de adequação do meio bucal de crianças e adolescentes. Estarão aptos para realizar a vigilância da cavidade bucal.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_78843190.jpg"
        },
        {
            "titulo": "Treinamento de força: Novas tendências para o desempenho esportivo",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Estudantes de graduação e professores das áreas da Educação Física, Medicina, Nutrição e Fisioterapia.",
            "beneficios": "O referido curso visa através da aplicação teórico-prática abordar novas estratégias para o desenvolvimento da força com a utilização de novas ferramentas científicas.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_120686975.jpg"
        },
        {
            "titulo": "Retreinamento musculoesquelético e desportivo",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados, Graduandos e professores das áreas de Fisioterapia e Educação Física.",
            "beneficios": "Visando o atual cenário da evolução do conhecimento das ciências da reabilitação, o presente curso vem com o intuito de trazer as mais atuais evidências com a aplicações práticas sobre como utilizar o exercício físco para retreinar os movimentos, direcionando o conteúdo para clientes que possuam dor aguda e crônica, LER/DORT, lesões traumato/ortopédicas, pré e pós-fisioterapico, lesões desportivas. Apresentando desde questões fundamentais à retreinamento através de prescrições de exercícios mais complexos para as incapacidades, a utilização de terapias e equipamentos e a orientação acerca do trabalho das diversidades por tras de cada situação, oferecendo respostas com fácil aplicação.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_69806858.jpg"
        },
        {
            "titulo": "Equalização de tensões miofasciais voltadas para o retreinamento de lesões",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados, graduandos e professores das áreas de Educação, Educação Física e Fisioterapia.",
            "beneficios": "Este curso tem como objetivo possibilitar aos alunos o domínio de uma das técnicas mais eficazes e utilizadas na promoção do retreinamento de lesões, e reforçar conhecimentos de biomecânica articular, miologia e cinesiologia, assim como toda a relação de padrão motor e neurofisiologia relacionada ao gesto motor. Essa necessidade é do atual momento do mercado de educação física e fisioterapia, onde o domínio do conhecimento do sistema miofascial e sua relação com a promoção de movimento está diferenciando os profissionais dessas áreas.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_32685534.jpg"
        },
        {
            "titulo": "Ventilação mecânica básica e interpretação de hemogasometria arterial",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos da Área da Saúde (Fisioterapia, Enfermagem, Medicina).",
            "beneficios": "Aprimoramento para manuseio da Ventilação Mecânica Convencional, assim como os cuidados necessários durante a realização da mesma. Análise e interpretação do exame gasométrico arterial. Ao final do curso, o aluno estará apto a entender os princípios de ventilação mecânica; compreender a diferença entre os modos ventilatórios convencionais; compreender os cuidados necessários durante a ventilação mecânica; avaliar e interpretar a hemogasometria arterial.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/dreamstime_xxl_122440564.jpg"
        },
        {
            "titulo": "Técnicas cromatográficas aplicadas à análises toxicológicas e medicamentos",
            "horario": "9h às 13h",
            "periodicidade": "Semanal (Sábado)",
            "cargaHoraria": "8 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Alunos de Graduação em Biomedicina, Farmácia, Química e áreas afins que pretendem atuar ou atuam em indústria farmacêutica, farmoquímica, química e análises toxicológicas.",
            "beneficios": "Capacitar os alunos das graduações de Bioquímica, Farmácia e Química a desenvolver conhecimentos específicos para atuarem na indústria farmacêutica,farmoquímica e química; gerando conhecimentos técnicos específicos contribuíndo para aprimoramento das atividades analíticas nos setores de controle da qualidade, pesquisa e desenvolvimento.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/dreamstime_xxl_98197825.jpg"
        },
        {
            "titulo": "Reabilitação em fisioterapia esportiva baseada em exercícios",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Acadêmicos de fisioterapia e fisioterapeutas formados.",
            "beneficios": "Ensinar possibilidades de avaliações e tratamentos baseados em exercícios, para disfunções/lesões comuns em traumato-ortopedia e em fisioterapia esportiva. Raciocínio acerca da evolução de exercícios para reabilitação de lesões traumato-ortopédicas e esportivas. Ao término do curso, o aluno terá novas ferramentas para melhorar sua abordagem baseada em cinesioterapia inerente às áreas citadas.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/dreamstime_xxl_129612659.jpg"
        },
        {
            "titulo": "Terapia manual em traumato-ortopedia e fisioterapia esportiva",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Acadêmicos de fisioterapia e fisioterapeutas formados.",
            "beneficios": "Ensinar possibilidades de avaliações e tratamentos baseados em terapia manual, para disfunções/lesões comuns em traumato-ortopedia e em fisioterapia esportiva. Aprimoramento da manualidade, fundamental para profissionais que se interessam ou atuam em fisioterapia traumato-ortopédica e esportiva. Ao término do curso, o aluno terá novas ferramentas para avaliação e tratamento das principais disfunções inerentes às áreas citadas.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/dreamstime_xxl_54258236.jpg"
        },
        {
            "titulo": "Avaliação musculoesquelética",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Acadêmicos de fisioterapia e fisioterapeutas formados.",
            "beneficios": "Aprimoramento do raciocínio acerca da avaliação musculoesquelética, abordando conceitos de cadeias lesionais e avaliação de seguimentos adjancentes. Ao término do curso, o aluno terá novas ferramentas para melhorar seu raciocínio dentro da avaliação, a começar por uma anamnese robusta e eficaz, seguindo para um exame físico bem detalhado e específico.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/dreamstime_xxl_67626973.jpg"
        },
        {
            "titulo": "Papel do eixo neuro imuno endócrino durante o estresse agudo",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "Não disponível no momento",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Estudantes da área da saúde que tenham cursado disciplinas de fisiologia, imunologia, farmacologia ou bioquímica durante a graduação. Além disso o tema pode despertar interesse para qualquer profissional que se submeta diariamente a situações de pânico ou estresse no ambiente familiar e profissional.",
            "beneficios": "O curso tem como proposta a compreensão das alterações fisiológicas, endócrinas e comportamentais decorrentes de situações agudas de estresse que acomete uma parcela cada vez maior da população em diferentes faixas etárias podendo levar ao desenvolvimento de complicações cardiovasculares dentre outras. Além disso, esse tema envolve a integração de diferentes disciplinas da área da saúde fornecendo assim ao estudante uma visão completa e detalhada sobre as alterações do equilíbrio do meio interno e as consequências neurohumorais e cognitivas em virtude do estresse.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/desconto-fatenp-20-maio-new.jpg"
        },
        {
            "titulo": "Atualização em clínica integrada avançada",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "64 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Alunos do 9º período de Odontologia e Cirurgiões Dentista.",
            "beneficios": "Os alunos em formação ,assim como os cirurgiões dentista generalistas  necessitam estar atualizados de acordo com as novas filosofias e técnicas que surgem na  odontologia moderna, visando atender o mercado de trabalho e as expectativas do paciente,  incrementando no seu dia clínico práticas e técnicas avançadas que cabem ao clínico geral.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/04/shutterstock_1052270132-2.jpg"
        },
        {
            "titulo": "Tratamento padrão ouro para gordura localizada: Criolipólise e Criofrequência",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados, Graduandos e Profissionais de Estética e afins.",
            "beneficios": "",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/04/tratamento-ouro-criolipolise.jpg"
        },
        {
            "titulo": "Atualização em dentística restauradora",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "96 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Cirurgiões-dentistas ou alunos do curso de graduação em Odontologia, que queiram aprofundar seus conhecimentos e desenvolver suas habilidades em Dentística Restauradora.",
            "beneficios": "O curso visa o aprimoramento das habilidades práticas clínicas, na área de Dentística Restauradora, empregando técnicas e materiais atuais, de fácil aplicabilidade tanto para o acadêmico de Odontologia como para o Clínico Geral.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/lVpBVnp7TsCFUagGvCkjWw_thumb_b4cb-1517.jpg"
        },
        {
            "titulo": "Atualização em periodontia clínica",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "40 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Alunos de graduação que tenham cursado o quinto período e cirurgiões dentistas formados em odontologia.",
            "beneficios": "As cirurgias periodontais e perimplantares estão cada vez mais presentes na rotina diária nos consultórios odontológicos, com isso aumenta a responsabilidade do cirurgião-dentista em conhecer as indicações, o planejamento e execução das mesmas. Uma ferramenta essencial nos dias atuais é planejamento digital que está inserido tanto na implantodontia quanto na periodontia, trazendo para o aluno uma alternativa que servirá de diferencial em seu consultório.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/Healthy-teeth-patient-at-dentist-office-dental-caries-prevention.jpeg"
        },
        {
            "titulo": "Atualização em periodontia e implantodontia clínica",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "50 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Alunos de graduação que tenham cursado o quinto período e Cirurgiões dentistas formados em odontologia.",
            "beneficios": "As cirurgias periodontais e perimplantares estão cada vez mais presentes na rotina diária nos consultórios odontológicos, com isso aumenta a responsabilidade do cirurgião-dentista em conhecer as indicações, o planejamento e execução das mesmas. Uma ferramenta essencial nos dias atuais é planejamento digital que está inserido tanto na implantodontia quanto na periodontia, trazendo para o aluno uma alternativa que servirá de diferencial em seu consultório.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/Close-up-of-patients-mouth-in-a-visit-to-the-dentist.jpeg"
        },
        {
            "titulo": "Coleta e remessa de materiais para exame – Veterinária",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos de Medicina Veterinária. Neste curso os participantes terão a oportunidade de praticar coleta de diversos tipos de materiais utilizados nos exames de rotina da clínica médica de animais de guarda e companhia.",
            "beneficios": "O aluno desenvolverá habilidades de manipulação instrumental, vias de conservação e de remessa, prontuários e terminologia técnica. Algumas questões que o aluno vivenciará no transcorrer do curso.  Possibilitará a avaliar os diversos graus de dificuldade na coleta solucionando-as com as técnicas apresentadas.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_548162731-2.jpg"
        },
        {
            "titulo": "Drenagem linfática aplicada ao pós-operatório corporal",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados, graduandos e profissionais de Estética e afins.",
            "beneficios": "O objetivo do curso é mostrar que a assistência no pós operatório é fundamental para a recuperação do paciente, com isso há necessidade de aprimoramento neste segmento.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_453315094-1-drenagem.jpg"
        },
        {
            "titulo": "Escovista avançado",
            "horario": "14h às 18h",
            "periodicidade": "Semanal (terça-feira e quinta-feira)",
            "cargaHoraria": "16 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Graduados e graduandos dos cursos de Estética, ou formados que atuem na área relacionada a beleza e bem estar.",
            "beneficios": "O desenvolvimento da percepção crítica dos alunos, com significativa melhora de suas habilidades. Como objetivo final de conhecer e aprofundar nas novas e diversas técnicas, tendo facilidade na aplicação dos conteúdos demonstrados.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_197226602-1-copia.jpg"
        },
        {
            "titulo": "Farmacoterapia respiratória",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "6 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados, Graduandos a partir do 3° período dos cursos de Medicina, Odontologia, Enfermagem, Farmácia e Profissionais já formados nestas áreas.",
            "beneficios": "",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/farmacologia-respiratoria-banner.jpg"
        },
        {
            "titulo": "Neuroanatomia radiológica seccional",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "12 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos dos cursos Tecnólogo em Radiologia, Medicina, Biomedicina, Biologia, Enfermagem, Fisioterapia, Educação Física, além de técnicos de Radiologia e Enfermagem.",
            "beneficios": "Um dos atrativos do Curso de Atualização em Neuroanatomia Radiológica Seccional é o preço acessível aliado à flexibilidade de horários, tendo em vista que a maior parte dos profissionais que buscam a educação continuada, estudam (graduação) e trabalham.  Além de todo o conhecimento adquirido e do contato com tecnologia de ponta, a realização do curso indica que o profissional não parou no tempo, que é uma pessoa em constante busca do conhecimento, e é esse profissional que o mercado busca hoje.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/neuro.jpg"
        },
        {
            "titulo": "Surgical anatomy",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Este curso foi cuidadosamente estudado para satisfazer as necessidades de educação continuada das área de Odontologia, Medicina e áreas afins.",
            "beneficios": "Por meio da dissecação e anatomia do cadáver durante o curso, os alunos terão acesso total as mais profundas estruturas da pele, vasos, veias, ossos e etc, com a orientação de exímios professores bucomaxilofaciais e cirurgião geral, experts em anatomia para dissecação de cadáver nas áreas de cabeça e pescoço. Proporcionará ao aluno um aprofundado conhecimento prático em anatomia e segurança clínica necessários para obtenção em excelência prática.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_1153763470-578x384-1.jpg"
        },
        {
            "titulo": "Atualização de tratamento endodôntico em molares",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduandos que já tenham cursado com aprovação a disciplina de Endodontia II e profissionais formados no curso superior de Odontologia em instituição de ensino reconhecida pelo MEC.",
            "beneficios": "A terapêutica endodôntica em molares se diferencia dos demais dentes em todas as etapas clínicas, desde a abertura coronária, passando pelo preparo químico mecânico, até à obturação endodôntica, o que torna sua execução mais desafiadora. Ao final do curso o aluno será capaz de empregar técnicas modernas, tais como, o uso de microscópio clínico, localizadores apicais, sistemas motorizados e técnicas obturadoras específicas para cada caso, fundamentadas cientificamente para a resolução eficaz do tratamento endodôntico em molares.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/TRATAMENTO-ENDODONTICO.jpg"
        },
        {
            "titulo": "Curso teórico e prático em coleta de sangue",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos dos cursos de Farmácia, Biologia, Biomedicina, Enfermagem e Medicina.",
            "beneficios": "Conteúdo Programático: Aprendizagem da técnica de coleta de sangue venoso; Postura profissional no ato da coleta de sangue; Noções de Biossegurança e métodos para coleta de sangue venoso; Aprendizagem do exame coagulograma aplicado na fase pré-analítica; Prática de teste do coagulograma na fase pré-analítica.",
            "area":"saude",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/02/coleta-sangue-banner.jpg"
        },
        {
            "titulo": "Excel aplicado a finanças",
            "horario": "9h às 17h",
            "periodicidade": "Semanal (sábado)",
            "cargaHoraria": "8 horas",
            "unidade": "Unidade Carioca",
            "publicoAlvo": "Estudantes e profissionais que necessitam aperfeiçoar seus conhecimentos em funções e ferramentas direcionadas a área financeira.",
            "beneficios": "Diferencial competitivo na busca por oportunidades de trabalho. Pode ser utilizado em qualquer segmento de negócios. Aplicável a qualquer atividade de uma empresa. Otimização e simplificação de tarefas complexas.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/08/shutterstock_1127962772.jpg"
        },
        {
            "titulo": "Controle de versão com Git e Github",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos e profissionais de Tecnologia da Informação interessados em desenvolvimento de software.",
            "beneficios": "Sistemas de controle de versão estão presentes em qualquer projeto de desenvolvimento de software. Trata-se de uma tecnologia fundamental em projetos de software de qualquer natureza. O Git é o sistema de controle de versão de arquivos mais utilizado no mundo, enquanto que o GitHub é o repositório de projetos baseado no Git mais popular entre os desenvolvedores de software. O GitHub, ainda, se apresenta como uma plataforma para divulgação do portfólio de projetos de desenvolvedores de software, sendo utilizado frequentemente por recrutadores para avaliar as habilidades de candidatos a vagas na área de desenvolvimento de software.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_59785001.jpg"
        },
        {
            "titulo": "Data science for software engineering",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos e profissionais de Tecnologia da Informação interessados em Ciência de Dados e em Engenharia de Software.",
            "beneficios": "A área de Ciência de Dados vem crescendo vertiginosamente. A indústria, de forma geral, carece de cientistas de dados que atuem nos mais variados segmentos. Em Engenharia de Software, particularmente, as perspectivas de aplicação das técnicas e ferramentas de Ciência de Dados são inúmeras, em especial no que diz respeito à construção de modelos preditivos de defeitos e de esforço em projetos de software.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/shutterstock_669226204.jpg"
        },
        {
            "titulo": "Tubulações industriais – Cálculos e projetos",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "7 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e Graduandos dos cursos de Engenharia em Geral, Química, Tecnólogos e Engenheiros.",
            "beneficios": "O presente curso propõe uma visão ampla e multidisciplinar do assunto, envolvendo conceitos teóricos, técnicos e de cálculos, o que em algumas ocasiões pode não ser tão detalhado em um curso de Graduação por ser um assunto específico.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/dreamstime_xxl_98123156.jpg"
        },
        {
            "titulo": "Introdução ao desenvolvimento de jogos com Javascript",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Profissionais e estudantes de Tecnologia da Informação interessados em desenvolvimento de jogos digitais, que possuam conhecimentos básicos de programação.",
            "beneficios": "O setor de games tem crescido uma média de 12% ao ano, nos últimos cinco anos, e há falta de mão de obra qualificada, por isso os profissionais são muito disputados. Este mercado é tão importante que, só no Brasil, temos mais de 66 milhões de gamers que movimentaram uma receita total de $1,3 bilhões em 2017. Mais do que apenas entretenimento, os games são utilizados como ferramentas pedagógicas em escolas e treinamentos empresariais.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/shutterstock_1146277802.jpg"
        },
        {
            "titulo": "Fotografia com celular para gerar conteúdo no instagram de moda",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "Não disponível no momento",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Estudantes e interessados em moda, redes sociais e fotografia.",
            "beneficios": "Ensinar ao aluno a desenvolver conteúdo para rede social de divulgação de moda (produtos ou serviços), abordando as funções básicas do aplicativo como posts, legendas, comentários, feed, stories, hashtags, interação e também como fazer boas fotos para tornar o perfil mais atrativo. A matéria-prima do Instagram é a imagem, vamos falar de iluminação, ângulo, composição para melhor mostrar o produto, cenário e tratamento de imagem com aplicativo de celular.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/shutterstock_410560561-edit.jpg"
        },
        {
            "titulo": "Introdução ao Power BI",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados,  graduandos ou alunos de pós-graduação de todas as áreas,  que desejam ampliar os seus conhecimentos em relação ao manuseio, análise e apresentação de dados.",
            "beneficios": "O profissional que domina a ferramenta Power BI está apto a produzir Dashboards (painéis de visualização de dados) interativos, que vão apoiar o processo de tomada de decisão com base nos fatos apresentados pela ferramenta.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/04/shutterstock_718643389.jpg"
        },
        {
            "titulo": "Power BI avançado",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Profissionais e Alunos de graduação ou pós-graduação de todas as áreas, que desejam ampliar os seus conhecimentos na ferramenta Power BI.",
            "beneficios": "O profissional que domina a ferramenta Power BI está apto a produzir Dashboards (painéis de visualização de dados) interativos, que vão apoiar o processo de tomada de decisão com base nos fatos apresentados pela ferramenta.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/04/shutterstock_1268632930-1.jpg"
        },
        {
            "titulo": "Perícia judicial",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "21 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Profissional graduado que deseje ampliar sua área de atuação com vistas a um mercado com demanda crescente, que desejam atuar de forma exclusiva ou paralelamente a outras atividades profissionais.",
            "beneficios": "É necessário possuir graduação de nível superior. O concluinte adquire formação necessária para atuar como perito judicial e assistente técnico, ampliar sua área de atuação profissional para perícias judiciais e assistência técnica.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/04/shutterstock_1303204486-2.jpg"
        },
        {
            "titulo": "Automação de processos por BPM/BPMS",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduação e pós-graduação na área técnica de negócios, gestão e engenharias.",
            "beneficios": "Adquirir conhecimento práticos e conceituais em automação de processos por BPM/BPMS, por meio de soluções rápidas e flexíveis para o mercado, alinhando-se aos conceitos da indústria 4.0, com integração de dados, áreas e indicadores.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/Successful-business-presentation-of-a-man-at-the-office.jpeg"
        },
        {
            "titulo": "Auditor interno de SGI – ISO 9001:2015, ISO 14001:2015 e ISO 45001:2018",
            "horario": "8h às 14h",
            "periodicidade": "Semanal (sábado)",
            "cargaHoraria": "24 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Graduados e graduandos dos cursos de Engenharia, Administração, Farmácia, Química, além de profissionais já formados, como líderes e supervisores que venham a atuar em Sistemas de Gestão Integrada.",
            "beneficios": "Desenvolver habilidades de auditoria interna nos participantes, que pode ser aplicada na auditoria de suas próprias organizações ou em organizações de terceiros. Interpretar as normas ISO 9001:2015, ISO 14001:2015, ISO 45001:2018 e ISO 19011:2012.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/auditor-interno-sgi.jpg"
        },
        {
            "titulo": "Condomínios sustentáveis",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados, graduandos e profissionais que desejam se aprimorar em Gestão de Obras, Reparos e Serviços de Instalação e Manutenção, em conformidade com procedimentos e recomendações sustentáveis.",
            "beneficios": "A gestão de obras, reparos e serviços de instalações e/ou manutenção precisam estar em conformidade com procedimentos e recomendações sustentáveis, para estarem de acordo com a legislação vigente.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/Condomínios-Sust.png"
        },
        {
            "titulo": "Curso básico de Corel Draw",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "12 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Curso livre para todos os interessados em conhecer a ferramenta.",
            "beneficios": "O curso visa auxiliar o participante a conhecer as ferramentas e o uso do software CorelDRAW, para a criação e edição de imagem vetorial, assim como material gráfico para aplicação em mídia impressa e/ou digital.  Busca também, apresentar e aperfeiçoar o aluno com o programa Corel Draw, preparando-o para realizar trabalhos de criação gráfica vetorial. O aluno conhecerá ferramentas para realizar trabalhos em diversos segmentos do mercado.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_441603820-copia.jpg"
        },
        {
            "titulo": "Curso básico em Ciências Forenses",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e Graduandos dos cursos de Química, Farmácia, Biologia, Medicina, Engenharias, Biomedicina, Direito, Tecnologia da Informação, interessados em aprender sobre a área de Investigação Científica Criminal.",
            "beneficios": "",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_450172012-1.jpg"
        },
        {
            "titulo": "Excel avançado",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "24 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Público em geral que tenham interesse na ferramenta e que possuam, como pré-requisito, domínio do Excel Básico (Funções contadoras: CONT.SE/ CONT.NUM/ CONT.VALORES/ CONT.VAZIO. Função SE/ Função SOMASE.S/ MÁXIMO, MÍNIMO, MEDIA, PERCENTUAL).",
            "beneficios": "O domínio do Excel é recomendado para diversas áreas e muitas das vezes é considerado como pré-requisito para um processo seletivo. Dominá-lo em um nível mais avançado é um forte diferencial no mercado de trabalho. Ao final do curso, o aluno será capaz de criar planilhas e relatórios mais eficientes para o gerenciamento das informações na sua área de atuação.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_509490142-1-copia.jpg"
        },
        {
            "titulo": "Excel básico",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "4 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Estudantes ou profissionais com conhecimentos básicos de Excel.",
            "beneficios": "O foco do curso é em aumentar a produtividade do aluno no uso do Excel. Serão apresentados atalhos, fórmulas e ferramentas disponíveis que agilizam as tarefas realizadas no dia a dia. O curso é inédito em seu viés de trabalhabilidade dos conceitos, fugindo do passo a passo dos conceitos ensinados em cursos de Excel tradicionais.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/7386661104_bf1f69a13e_c.jpg"
        },
        {
            "titulo": "Excel básico ao intermediário",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "24 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Público em geral que deseja aprender a manusear a ferramenta.",
            "beneficios": "Conhecimentos básicos de informática.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_1067559380-1.jpg"
        },
        {
            "titulo": "Ms Project",
            "horario": "8h às 14h",
            "periodicidade": "Semanal (sábado)",
            "cargaHoraria": "24 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Engenheiros, Arquitetos e demais profissionais que atuam ou pretendem atuar com gerenciamento de projetos, adicionando os conhecimentos básicos desta difundida ferramente de gestão de cronogramas. É necessário ter concluindo ou estar cursando a graduação em qualquer das Engenharias, Arquitetura ou áreas afins, conhecimentos de windows, excel e internet.",
            "beneficios": "O curso visa introduzir os conceitos básicos do Gerenciamento de Projetos conforme boas práticas do PMBOK,  e fazer o emprego e utilização da ferramenta MS Project na sua gestão.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_715110601-copia1.jpg"
        },
        {
            "titulo": "Técnicas de caracterização de materiais poliméricos",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Pós-Graduados, Graduados, Graduandos e tecnólogos de qualquer área que utilizam técnicas de caracterização de materiais poliméricos.",
            "beneficios": "O aluno deverá ter conhecimento básico de química e materiais poliméricos. Será de grande benefício para o aluno, adquirir conhecimento das técnicas de caracterização e os equipamentos utilizados. Assim como, interpretação de resultados e análises gráficas para estudos de caracterização simples e complexos como envelhecimentos térmicos, envelhecimento acelerado, comparação de propriedades mecânicas e térmicas entre diferentes materiais.",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock12.jpg"
        },
        {
            "titulo": "Produção de cerveja artesanal – Básico",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados, graduandos e tecnólogos de qualquer área de atuação que tenham interesse em produzir cerveja em casa.",
            "beneficios": "",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/producao-cerveja-artesanal-banner.jpg"
        },
        {
            "titulo": "Projetos elétricos prediais",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "24 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos dos cursos de Arquitetura e Engenharia, a partir do sexto período, com pré-requisito de Elétrica cumprido ou cursando.",
            "beneficios": "",
            "area": "tecnologia",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/red.jpg"
        },
        {
            "titulo": "Marketing pessoal e desenvolvimento profissional",
            "horario": "19h às 22h",
            "periodicidade": "Semanal (Segunda-Feiras a Quinta-Feira)",
            "cargaHoraria": "12 horas",
            "unidade": "Campus II - Rio de Janeiro-Lapa",
            "publicoAlvo": "Profissionais em geral, que buscam oportunidades de desenvolvimento profissional e utilização do marketing pessoal.",
            "beneficios": "Ensinar o indivíduo a se valorizar, melhorar sua imagem, ganhar destaque na sua área profissional, desenvolver autoconfiança para o alcance de sucesso, através de suas qualidades, habilidades e atitudes.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/10/marketing-pessoal-desenvolvimento.jpg"
        },
        {
            "titulo": "Atualização em harmonização orofacial",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "52 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Cirurgiões-Dentistas, Médicos e Biomédicos. Estudantes de Odontologia, Estudantes de Medicina e Estudantes de Biomedicina.",
            "beneficios": "A Harmonização Orofacial é uma área da Odontologia que tem como objetivo restabelecer o equilíbrio estético-funcional da face do paciente por meio de procedimentos e técnicas realizados nessa região e que complementam as diversas especialidades odontológicas. O equilíbrio e a harmonia facial estão intimamente associados a estruturas e características da cabeça e pescoço, volume e posicionamento da estrutura óssea, bem como de tecidos moles, estrutura da derme, condição periodontal e dentária, entre outras. Essas características são dinâmicas, modificam ao longo da vida pelo processo de envelhecimento de cada indivíduo. Logo, o Cirurgião-Dentista deve estar preparado pra prevenir, manter e promover o equilíbrio estético-funcional da face de pacientes que apresentem disfunções ou que tenham perdido a harmonia orofacial em função do processo de envelhecimento facial.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/09/shutterstock_1104083144.jpg"
        },
        {
            "titulo": "Legalização de baixa, alterações contratuais e transformações de natureza jurídica de empresas",
            "horario": "09:30h às 15:30h",
            "periodicidade": "Semanal (Terças-Feiras e Quintas-Feiras)",
            "cargaHoraria": "12 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Profissionais e estudante de Ciências Contábeis.",
            "beneficios": "Apresentar as diversas possibilidades da existência das transformações entre naturezas jurídicas (MEI, Empresário Individual, Eireli, Sociedade Ltda.). Identificar as variadas razões que resultam em Alterações Contratuais, e o funcionamento das Baixas, demonstrando o comportamento dos órgãos de registro para legalização de tais eventos. Orientar e capacitar o participante, quanto ao registro e solução de possíveis exigências dos atos, mostrando o passo a passo para sua a legalização junto aos órgãos, tornando o aluno capaz de conduzir o processo de registro das Baixas, Alterações Contratuais e transformações.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/09/shutterstock_334043390.jpg"
        },
        {
            "titulo": "Legalização de abertura de empresas",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "15 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Profissionais e estudante de Ciências Contábeis.",
            "beneficios": "Descrever os conceitos básicos, assim como fatores positivos e negativos dos diversos tipos de natureza jurídica existentes, além de demonstrar o passo a passo para abertura e legalização dos empreendimentos, deixando o aluno capaz de conduzir tal processo de forma consistente.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/09/shutterstock_334043420.jpg"
        },
        {
            "titulo": "Conquistando a excelência no atendimento ao cliente",
            "horario": "9h às 13h",
            "periodicidade": "Semanal (Sábado)",
            "cargaHoraria": "8 horas",
            "unidade": "Unidade Carioca",
            "publicoAlvo": "Público em geral que tenham como atividade principal o atendimento ao cliente tais como: Atendentes, Recepcionistas, Secretárias, Assistentes entre outros.",
            "beneficios": "O curso visa demonstrar técnicas assertivas para cada tipo de canal de comunicação utilizado pelas instituições.Ademais, ter excelência no atendimento pode se tornar uma vantagem competitiva entre os concorrentes. Logo, um profissional bem capacitado pode atuar de forma estratégia contribuindo para o alcance dos objetivos organizacionais.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/08/shutterstock_320667095.jpg"
        },
        {
            "titulo": "Curso de formação de perito judicial",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "24 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Qualquer profissional com registro em seu conselho de classe.",
            "beneficios": "O curso possibilita os profissionais de diversas áreas a se qualificarem para atuar como peritos judiciais nas esferas estaduais e federais. Os profissionais terão uma visão do rito processual , do comportamento do perito, bem como as formas de se cadastrar junto as tribunais.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/08/shutterstock_1167639382.jpg"
        },
        {
            "titulo": "Principais técnicas de análise de ações",
            "horario": "9h às 12:30h",
            "periodicidade": "Semanal (Sábado)",
            "cargaHoraria": "6 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Investidores em geral que tenham interesse em selecionar melhor seus investimentos, graduandos dos cursos de Administração, Ciências Contábeis e Economia que tenham interesse em conhecer as diferentes técnicas de análise de ações.",
            "beneficios": "Trata-se de um curso introdutório acerca dos principais tópicos relacionados às técnicas mais utilizadas na análise de ações (fundamentalista e técnica).",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/08/shutterstock_750493204.jpg"
        },
        {
            "titulo": "Instagram para empreendedores",
            "horario": "8h às 15h",
            "periodicidade": "Semanal (Sábado)",
            "cargaHoraria": "6 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Empreendedores, profissionais de mercado e público em geral que tenha interesse no tema.",
            "beneficios": "Proporcionar aos discentes o conhecimento sobre o potencial do Instagram, uma rede social com mais de um bilhão de seguidores e muitas oportunidades de negócio. O curso buscará capacitar os participantes para obterem conhecimento prático sobre a rede social e as principais estratégias voltadas para alavancar sua empresa no meio digital.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/08/shutterstock_1213840051.jpg"
        },
        {
            "titulo": "Excel aplicado a finanças",
            "horario": "9h às 17h",
            "periodicidade": "Semanal (sábado)",
            "cargaHoraria": "8 horas",
            "unidade": "Unidade Carioca",
            "publicoAlvo": "Estudantes e profissionais que necessitam aperfeiçoar seus conhecimentos em funções e ferramentas direcionadas a área financeira.",
            "beneficios": "Diferencial competitivo na busca por oportunidades de trabalho. Pode ser utilizado em qualquer segmento de negócios. Aplicável a qualquer atividade de uma empresa. Otimização e simplificação de tarefas complexas.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/08/shutterstock_1127962772.jpg"
        },
        {
            "titulo": "Auditor interno de compliance (Norma ISO 19.600) e antissuborno (Norma ISO 37.001)",
            "horario": "08h às 14h",
            "periodicidade": "Semanal (Sábado)",
            "cargaHoraria": "24 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Profissionais que atuam na auditoria, implantação e manutenção de sistemas de gestão. Pessoas de qualquer área que desejam atuar com sistemas de gestão e em especial Compliance e Antissuborno.",
            "beneficios": "Contribuir para o combate ao suborno através de uma cultura de integridade, conformidade com as leis e regulamentações aplicáveis e com os requisitos das normas ISO 37001 e ISO 19600. Sendo capazes de auditar tanto sistemas implantados, como ser um propulsor da cultura de Compliance e Antissuborno, pois a auditoria constitui uma ótima ferramenta gerencial utilizada na Gestão de Sistemas de Gestão e promove a detecção de oportunidades de melhoria envolvendo a empresa num processo de atendimento às normas e legislação vigentes com transparência, além de capacitar o aluno na interpretação e implementação dos requisitos da certificação, e proporcionando uma visão abrangente sobre os conceitos, fundamentos e princípios da gestão antissuborno.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/08/shutterstock_1203030571.jpg"
        },
        {
            "titulo": "Finanças pessoais: Domando a sua vida financeira",
            "horario": "8h às 12h",
            "periodicidade": "Semanal (Segunda-Feira, Terça-Feira e Quarta-Feira)",
            "cargaHoraria": "12 horas",
            "unidade": "Campus II - Rio de Janeiro-Lapa",
            "publicoAlvo": "Graduados e graduandos em Administração, Ciências Contábeis, Engenharias, Gestão e áreas correlatas, pessoas envolvidas ou interessadas em desempenho de investimentos de capital.",
            "beneficios": "Conhecer alternativas disponíveis no mercado para sanar as dívidas pessoais e construir uma vida financeira equilibrada, trabalhando sua mente para um comportamento mais adequado para a sua realidade social e econômica. Conhecimento das alternativas de investimento disponíveis no mercado: renda fixa e renda variável.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/07/dreamstime_xxl_152740790.jpg"
        },
        {
            "titulo": "Direito administrativo militar",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "24 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos do curso de Direito, além de Advogados (privados e públicos) que militam na Justiça Militar Estadual e Federal, que buscam atualização em Direito Militar.",
            "beneficios": "O exercício da função militar possui especificidades, decorrentes de sua natureza e características, que criam para os militares que a desempenham um regime de especial sujeição com o Estado, com direitos, prerrogativas e deveres que, não sua maioria, não são assegurados aos servidores civis. O curso tem por objetivo um estudo específico do direito administrativo militar, por objeto regular e disciplinar o exercício da função militar (espécie de função administrativa), a organização das Forças Armadas e das Forças Auxiliares (Exército, Marinha, Aeronáutica, Polícia Militar e Corpo de Bombeiros Militares), bem como a relação funcional dos agentes públicos militares (regime disciplinar e regime previdenciário).",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/shutterstock_1021395283.jpg"
        },
        {
            "titulo": "Departamento pessoal avançado",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Assistentes, Auxiliares e Chefes de Departamento de Pessoal (DP), Administradores, Advogados, Auditores, Empresários e empregados de Recursos Humanos e demais interessados na Rotina de Pessoal.",
            "beneficios": "Capacitar os participantes na realização das atividades pertinentes a área de Departamento de Pessoal, conhecer a Legislação Trabalhista atual e identificar os direitos e deveres do empregado e empregador.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/shutterstock_1332814697.jpg"
        },
        {
            "titulo": "Departamento pessoal básico para iniciantes",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Assistentes, Auxiliares e Chefes de Departamento de Pessoal (DP), Administradores, Advogados, Auditores, Empresários e empregados de Recursos Humanos e demais interessados na Rotina de Pessoal.",
            "beneficios": "O curso tem como objetivo oferecer aos participantes conhecimentos e ferramentas aplicáveis no dia a dia do Departamento Pessoal, de forma prática, que propiciem o aprimoramento de suas rotinas diárias e mensais com atenção aos cálculos.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/shutterstock_1332821684.jpg"
        },
        {
            "titulo": "Dos crimes de corrupção",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "20 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Profissionais de carreira jurídica (Estudantes de Direito, Advogados, membros do Ministério Público, do Poder Judiciário, da Defensoria Pública, de órgãos de Segurança Pública e respectivos servidores), assim como empresários ou profissionais da iniciativa privada que pretendam se resguardar de tais práticas criminosas. Indicado também aos estudantes de graduação e pós-graduação nos cursos de Administração e/ou Gestão Pública.",
            "beneficios": "Este curso tem por escopo um estudo específico e aprofundado dos Crimes praticados contra a Administração Pública em Geral, não apenas em sua acepção estritamente jurídica, como também em suas mais variadas dimensões (ética, moral, patrimonial, social etc).Na observação destas diversas óticas, buscar-se-á, além de um estudo minucioso – inicialmente técnico-jurídico – dos variados tipos penais no Código Penal e das leis extravagantes, despertar no discente, a partir de uma perspectiva crítica, uma série de reflexões político-sociais que possam contribuir para a criação de novos mecanismos de política criminal no combate e prevenção dos atos que lesam o patrimônio e a moral administrativa. É também objetivo deste curso intercambiar os conceitos aplicáveis aos crimes contra a administração pública com diversos institutos do Direito Administrativo, tais como a classificação estrita e ampla de servidor público, a Organização Política e Administrativa do Estado, os Serviços Públicos, Contratos e Licitações etc.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_137758729.jpg"
        },
        {
            "titulo": "Liderança de equipe: Como superar os desafios dos tempos modernos",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Egressos e alunos dos cursos de Gestão como, Administração, Logística, RH, Marketing, Gestão Financeira e Publicidade e Propaganda que tenham como objetivo seguir carreira em grandes player’s, seja na indústria de alimentos, bebidas, eletroeletrônicos e farmacêutica. O profissional responsável pela gestão comercial em empresas de médio e grande porte, pode obter ganhos salariais entre R$ 10.000,00 e R$ 18.000,00.",
            "beneficios": "O curso tem como objetivo preparar o seu egresso para as crescentes demandas do mercado, entre elas, a gestão das grandes contas. Considerando que 80% dos negócios das grandes marcas, concentram-se em 20% dos seus clientes, torna-se indispensável prover os profissionais com informações que os farão fazer parte de um seleto grupo de talentos que as organizações demandam. O egresso ira disputar oportunidades no mercado, levando consigo um grande diferencial.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_111070697.jpg"
        },
        {
            "titulo": "Gestão estratégica de micro e pequenas empresas",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Empreendedores, empresários, profissionais que exerçam cargo de gestão em suas respectivas empresas, alunos de Graduação e Pós-Graduação que tenham interesse no tema.",
            "beneficios": "Este curso tem como objetivo proporcionar um conjunto de conhecimentos que lhes permitam ter maiores condições de gerenciamento de seu negócio, de modo a aumentar a capacidade de manutenção da empresa num ambiente mercadológico altamente dinâmico e competitivo. Para tanto, o curso buscará capacitar os participantes para obterem conhecimento prático das principais técnicas e ferramentas de Gestão Empresarial.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_52708158.jpg"
        },
        {
            "titulo": "Marketing digital e vendas",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Empreendedores, empresários, profissionais que exerçam cargo de gestão comercial em suas respectivas empresas, alunos de graduação e pós-graduação que tenham interesse no tema.",
            "beneficios": "Este curso tem como objetivo proporcionar aos profissionais da área comercial, empreendedores e empresários um conjunto de conhecimentos que lhes permitam ter maiores condições de expansão de seus respectivos negócios, de modo a aumentar a capacidade de prospecção de clientes num ambiente mercadológico altamente dinâmico e competitivo. O curso buscará capacitar os participantes para obterem conhecimento prático das principais técnicas e ferramentas de marketing digital e vendas.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/06/dreamstime_xxl_76005666.jpg"
        },
        {
            "titulo": "Valuation – Avaliação de empresas",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "12 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Estudantes e profissionais que atuem e/ou possuam interesse em entender o processo de avaliação de empresas e projetos.",
            "beneficios": "Proporcionar conhecimentos técnicos na área de finanças e apresentar os principais métodos de avaliação de empresas. Oportunidades de compra e venda de empresas, oportunidades de compra e venda de participações em negócios, fusões com outras empresas, dissoluções societárias, indicadores estratégicos (Avaliação dos intangíveis/Marcas/Capital Intelectual).",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/dreamstime_xxl_137896145.jpg"
        },
        {
            "titulo": "Workshop – Alcance seus objetivos com dicas e técnicas de coaching",
            "horario": "19h às 21h",
            "periodicidade": "Semanal (Terça e quarta-feira)",
            "cargaHoraria": "4 horas",
            "unidade": "Unidade Carioca",
            "publicoAlvo": "Para alcançarmos nossos objetivos são necessárias algumas atitudes, por exemplo, abdicarmos e mudarmos de hábitos que não nos levam à lugar algum. E para isto ocorrer, devemos começar por saber quais são esses hábitos e o que devemos fazer para mudá-los. Com a necessidade de cada vez mais as pessoas terem Foco para alcançarem seus objetivos, este Workshop traz dicas e técnicas para que os participantes comecem a alterarem hábitos que interferem diretamente no Foco.",
            "beneficios": "Alunos, Egressos, Concursandos e demais pessoas que estejam interessados em mudanças de hábitos para alcançarem seus objetivos.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/shutterstock_627628097-edit.jpg"
        },
        {
            "titulo": "Workshop – Inglês para a área de engenharia offshore",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Um workshop exclusivamente para profissionais da área de Petróleo e Gás.",
            "beneficios": "Através de mine curso corporativo, o profissional se torna fluente no Inglês de maneira contextualizada para a sua área de atuação, o que contribui para seu crescimento pessoal e profissional.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/05/shutterstock_217119214-edit.jpg"
        },
        {
            "titulo": "Capacitação gerencial",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduandos de todos os cursos que desejam galgar a carreira Gerencial, além de Gerentes e Supervisores que queiram aprimorar seu desempenho na Gestão Empresarial.",
            "beneficios": "",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/capacitacao-gerencial-banner.jpg"
        },
        {
            "titulo": "Auditor interno de SGI – ISO 9001:2015, ISO 14001:2015 e ISO 45001:2018",
            "horario": "8h às 14h",
            "periodicidade": "Semanal (sábado)",
            "cargaHoraria": "24 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Graduados e graduandos dos cursos de Engenharia, Administração, Farmácia, Química, além de profissionais já formados, como líderes e supervisores que venham a atuar em Sistemas de Gestão Integrada.",
            "beneficios": "Desenvolver habilidades de auditoria interna nos participantes, que pode ser aplicada na auditoria de suas próprias organizações ou em organizações de terceiros. Interpretar as normas ISO 9001:2015, ISO 14001:2015, ISO 45001:2018 e ISO 19011:2012.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/auditor-interno-sgi.jpg"
        },
        {
            "titulo": "Comunicação irresístivel: Como influenciar pessoas e remover objeções para conquistar objetivos",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Executivos, gestores, autônomos, empresários e profissionais que desejam se aprimorar em diferentes formas de se comunicar e se relacionar com seu público alvo.",
            "beneficios": "Comunicar com objetividade e precisão, utilizando ferramentas verbais e não verbais da PNL, desenvolver sua capacidade de criar sintonia e empatia genuína na comunicação, além de ampliar sua flexibilidade comportamental na comunicação e mostrar estratégias eficientes para dar e receber feedback.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_598993493-1-copia.jpg"
        },
        {
            "titulo": "KPI's na cadeia de suprimentos",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Gestores, profissionais em geral e/ou alunos de Administração, Logística e SCM que queiram se capacitar e/ou aprimorar suas competências como gestor da cadeia de suprimentos.",
            "beneficios": "No âmbito corporativo, a mensuração do desempenho encontra aplicação na detecção da capacidade da empresa em gerenciar as variáveis críticas e em proporcionar uma visão das condições projetadas para o futuro. No atual contexto competitivo, a definição de um sistema de medidas que visam administrar e melhorar os resultados das empresas é uma questão extremamente importante, medir o desempenho significa comparar os resultados obtidos com os planejados.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/556-1-copia.jpg"
        },
        {
            "titulo": "Implantação do e-Social na prática",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Graduados e graduandos dos cursos de RH, Administração, além de profissionais que necessitam implementar o novo sistema e-Social ou que já implementaram, como forma de se atualizar.",
            "beneficios": "O objetivo é orientar sobre o novo sistema e-Social que será implementado pelo governo como ferramenta de controle das obrigações trabalhistas e previdenciárias pelas empresas.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/shutterstock_778472458-1-1.jpg"
        },
        {
            "titulo": "Oficina de aquarela",
            "horario": "9h às 13h",
            "periodicidade": "Semanal (Sábado)",
            "cargaHoraria": "8 horas",
            "unidade": "Campus I – Duque de Caxias",
            "publicoAlvo": "Graduados e Graduandos, além de profissionais do ramo da Moda.",
            "beneficios": "Nesse curso abordaremos de forma prática todos as técnicas de pintura em aquarela, tendo como ênfase a aplicação da aquarela em ilustrações de moda. Partindo da composição, iremos estudar estilos, como: Criação, textura, perspectiva e pintura. Cada estudante poderá ilustrar suas peças dentro do seu próprio estilo. Com isso, buscamos maior produtividade individual e da sala, fazendo com que as aulas se tornem mais dinâmicas e prazerosas para todos.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/4885545.jpg"
        },
        {
            "titulo": "Planejamento de vendas e gestão da equipe comercial",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "16 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Egressos e alunos dos cursos de gestão como, Administração, Logística, RH, Marketing, Gestão Financeira e Publicidade e Propaganda que tenham como objetivo seguir carreira em grandes player’s, seja na indústria de alimentos, bebidas, eletroeletrônicos e farmacêutica. O profissional responsável pela gestão comercial em empresas de médio e grande porte, pode obter ganhos salariais entre R$ 10.000,00 e R$ 18.000,00.",
            "beneficios": "O curso tem como objetivo preparar o seu egresso para as crescentes demandas do mercado, entre elas, a gestão das grandes contas. Considerando que 80% dos negócios das grandes marcas, concentram-se em 20% dos seus clientes, torna-se indispensável prover os profissionais com informações que os farão fazer parte de um seleto grupo de talentos que as organizações demandam. O egresso ira disputar oportunidades no mercado, levando consigo um grande diferencial.",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/36.jpg"
        },
        {
            "titulo": "Preenchimento de declaração IRPF",
            "horario": "Não disponível no momento",
            "periodicidade": "Não disponível no momento",
            "cargaHoraria": "8 horas",
            "unidade": "Não disponível no momento",
            "publicoAlvo": "Contadores, Técnicos contábeis, graduandos em Ciências Contábeis e pessoas físicas interessadas em aprender sobre o preenchimento da sua própria declaração de IRPF.",
            "beneficios": "",
            "area": "sociais e aplicadas",
            "imagem": "http://www.unigranrio.com.br/cursos-de-atualizacao/wp-content/uploads/2019/03/sh.jpg"
        }
    ];
}